### ISSUE TITLE
Not Able to Download New Attributes

### ISSUE THREAD

**Issue by D-sizzle** [jburkhardt/RAdwords#10]
There are a few relatively new attributes that I am not able to download through RAdwords. The "Est. add. clicks/wk" (-50%, +50%, +300%), "Est. add. cost/wk" (-50%, +50%, +300%), and "Base max. CPC" attributes would be super helpful for the Keywords and Product Partition reports. You can currently download them manually from the AdWords reporting UI. Any way we can pull these for unique keyword and product group in RAdwords?

**Comment by jburkhardt** [comment]
Hey,

unfortunately neither of the metrics you mentioned are available via the API yet. Here is a complete overview of the reports and metrics you can pull with the current API version:

https://developers.google.com/adwords/api/docs/appendix/reports

If the attributes will be available in a future API version, you can pull them with RAdwords of course.

With ```reports()``` you can get an overview of all the report types. ```metrics("KEYWORDS_PERFORMANCE_REPORT")``` lists all attributes for the keyword report.

Hope that helps!
Johannes
