### ISSUE TITLE
Connecting using RAdwords library and using doAuth gives error

### ISSUE THREAD

**Issue by Nayyarkazmi** [jburkhardt/RAdwords#100]
I have been trying to connect to Adwords Account using RAdwords, but I get the following error on doAuth():

Error in rjson::fromJSON(RCurl::postForm("https://accounts.google.com/o/oauth2/token", : STRING_ELT() can only be applied to a 'character vector', not a 'raw'

I have the correct credentials and Developer's token, but I am still unable to resolve the problem. I am using windows 7. The traceback is as follows:

> traceback()
    4: .Call("fromJSON", json_str, unexpected.escape, simplify, PACKAGE = "rjson")
    3: rjson::fromJSON(RCurl::postForm("https://accounts.google.com/o/oauth2/token", 
       .opts = opts, code = credlist$c.token, client_id = credlist$c.id, 
       client_secret = credlist$c.secret, redirect_uri = "urn:ietf:wg:oauth:2.0:oob", 
       grant_type = "authorization_code", style = "POST"))
    2: loadToken(credentials)
    1: doAuth()
Looked and tried all options from other similar questions, e.g.: using suggestions), I have also installed this version of RAdwords.

install_github('jburkhardt/RAdwords', ref = "refresh_token_raw_data")

I have asked this question on stackoverflow as well: https://stackoverflow.com/questions/52316730/connecting-using-radwords-library-and-using-doauth-gives-error

**Comment by mbannert** [comment]
interestingly, there is calls to rjson and to RJSONIO. Are we really using both @jburkhardt ? 
If so, we should change that.

**Comment by jburkhardt** [comment]
@Nayyarkazmi I committed a bug fix in a new branch **bugfix_char_to_raw**.
Could you please reinstall **RAdwords** from this branch and test again. I hope it solves your issue:
```R
install_github('jburkhardt/RAdwords', ref = "bugfix_char_to_raw")
```

**Comment by jburkhardt** [comment]
@Nayyarkazmi Any updates?
