### ISSUE TITLE
getauth

### ISSUE THREAD

**Issue by dancsvfd** [jburkhardt/RAdwords#12]
I've just downloaded and installed R, then I've run require(devtools) install_github('jburkhardt/RAdwords') and got a few success messages. But when I try to run doauth() it returns an error saying that it couldn't find the function "getAuth". Is there some intermediate step I should have done before doauth? Thanks a lot for this project!

**Comment by jburkhardt** [comment]
Could you make sure to run the authentication function with the correct capitalisation: `doAuth()`.

You have installed the development version of the package from github. This works fine for me on different operating systems and R Versions. There is a stable package version on cran as well. Just reinstall: `install.package("RAdwords")`

Without any code it is difficult to reproduce your problem. Let me know if you succeed.
