### ISSUE TITLE
CAMPAIGN_SHARED_SET_REPORT:DURING_CLAUSE_REQUIRES_DATE_COLUMN

### ISSUE THREAD

**Issue by john-niche** [jburkhardt/RAdwords#121]
Hello --

I was trying to get a list of campaigns and their associated negative keyword lists using the CAMPAIGN_SHARED_SET_REPORT and got the following error:

`"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><reportDownloadError><ApiError><type>QueryError.DURING_CLAUSE_REQUIRES_DATE_COLUMN</type><trigger></trigger><fieldPath></fieldPath></ApiError></reportDownloadError>"`

For context, my code is listed below:

```
google_auth <- doAuth()
start<-"2019-01-01"
end<-"2020-01-01"

body <- statement(select = c("AccountDescriptiveName","CampaignId","CampaignName","CampaignStatus","ExternalCustomerId","SharedSetId","SharedSetName","SharedSetType","Status"),
                     report = "CAMPAIGN_SHARED_SET_REPORT",
                     where="***",
                     start=start,
                     end=end)

data <- getData(clientCustomerId='****-***-***',
                   google_auth=google_auth,
                   statement=body)
```

I believe this is similar to issues 110 and 94. I was able to resolve this locally on my computer by appending 'CAMPAIGN_SHARED_REPORT' to the code block in the statement() function to ensure that the AdWords query did not include a during clause (example below, following '#reports without statistics and date column' comment. I'm not sure if this quick fix would impact other parts of the code, though.

```
# reports without statistics and date column
  if(report %in% c("LABEL_REPORT",
                   "CAMPAIGN_NEGATIVE_KEYWORDS_PERFORMANCE_REPORT",
                   "CAMPAIGN_NEGATIVE_LOCATIONS_REPORT",
                   "CAMPAIGN_NEGATIVE_PLACEMENTS_PERFORMANCE_REPORT",
                   "CAMPAIGN_SHARED_SET_REPORT"
                   )){
    body <- sprintf("__rdquery=SELECT+%s+FROM+%s&__fmt=%s",selectA,report,fmt)
    print(sprintf("The Adwords API does not support date ranges in the %s. Thus, date ranges will be ignored.", report))
  }
  # attach report Type, compression and apiVersion as attributes of body
  attr(body,"reportType") <- report
  attr(body,"compressed") <- compress
  attr(body,"apiVersion") <- apiVersion
  # return
  body
```

Sorry if I'm missing anything obvious here!

**Comment by jburkhardt** [comment]
@john-niche Thank you for discovering this issue!

I created a feature branch that should fix the issue with the requested report type `CAMPAIGN_SHARED_SET_REPORT`.

Could you please reinstall the **RAdwords** package from the new branch `report_wt_date` and test your original code again?

```R
library(devtools)
install_github("jburkhardt/RAdwords", ref="report_wt_date")
```

**Comment by john-niche** [comment]
That worked! Here's the output (just hid the customer ID we use):

`> library(devtools)
Loading required package: usethis
Warning message:
package ‘devtools’ was built under R version 3.6.2 
> install_github("jburkhardt/RAdwords", ref="report_wt_date")
Skipping install of 'RAdwords' from a github remote, the SHA1 (35cbd9e1) has not changed since last install.
  Use `force = TRUE` to force installation
> library(RAdwords)
> 
> 
> google_auth <- doAuth()
> start<-"2019-01-01"
> end<-"2020-01-01"
> 
> body <- statement(select = c("AccountDescriptiveName","CampaignId","CampaignName","CampaignStatus","ExternalCustomerId","SharedSetId","SharedSetName","SharedSetType","Status"),
+                   report = "CAMPAIGN_SHARED_SET_REPORT",
+                   start=start,
+                   end=end)
[1] "The Adwords API does not support date ranges in the CAMPAIGN_SHARED_SET_REPORT. Thus, date ranges will be ignored."
> 
> data <- getData(clientCustomerId=***,
+                 google_auth=google_auth,
+                 statement=body)`

**Comment by jburkhardt** [comment]
@john-niche Great! Thanks a lot for your support!
