### ISSUE TITLE
Campaign reports

### ISSUE THREAD

**Issue by joggopops** [jburkhardt/RAdwords#126]
Hello!

I'm having trouble extracting different campaigns from the same account. 
I'm trying to extract both a search campaign and a local campaign from the same ID.

However, I'm only getting the cost of the search campaign - not including the local campaign.

I've tried using ACCOUNT_PERFORMANCE_REPORT AND CAMPAIGN_PERFORMANCE_REPORT.

My code looks like this:
id <- xxx

body_label <- statement(select=c('ExternalCustomerId','Cost'), 
                        report="ACCOUNT_PERFORMANCE_REPORT",
                        start="2021-08-01",
                        end="2021-08-31")

data_label <- getData(clientCustomerId=id,
                      google_auth=adwords_auth,
                      statement=body_label, #object created with statement()
                      transformation = T, #data are transformed from xml text to R dataframe
                      changeNames = T)

Thank you in advance

**Comment by jburkhardt** [comment]
Hi @joggopops,
thank you for raising this question!
**RAdwords** connects with the latest version of the **Adwords** API `v201809`. Unfortunately, this API version does not support local campaigns. You can read more about it in the Google Ads Support here: https://groups.google.com/g/adwords-api/c/6l6PmmBu7x8
