### ISSUE TITLE
NAs introduced by coercion 

### ISSUE THREAD

**Issue by chipoglesby** [jburkhardt/RAdwords#15]
I keep getting errors when trying to download the Headline, Description line 1 and destination url for search ads:

Here's my statement:
body <- statement(select=c('AccountDescriptiveName','CampaignName','AdGroupName','Headline','Description1','Description2','DisplayUrl','CreativeDestinationUrl'),
                  report="AD_PERFORMANCE_REPORT",
                  start=thirtydays,
                  end=yesterday)

Any ideas what might be causing this to happen?

**Comment by mbannert** [comment]
can you run debug(yourfunction) ? NA introduced by coercion is quite a general R error.

**Comment by jburkhardt** [comment]
There occured a conflict in transformation of the raw data if the Ad Text data (Headline, Desciption!, etc.) contain "%".
I fixed the problem.
@chipoglesby: Reinstall the package from my github repository. You shouldn`t get NAs with the new version.

**Comment by chipoglesby** [comment]
Just now saw this. Thank you for your help @mbannert and @jburkhardt.
