### ISSUE TITLE
ACCOUNT_PERFORMANCE_REPORT Showing NA's for Conversion Value

### ISSUE THREAD

**Issue by D-sizzle** [jburkhardt/RAdwords#16]
I've been running the same script for a while. Conversion value is no longer being passed and resulting in NAs. I receive the Warning message: NAs introduced by coercion. Here is my script.

    # specify date range, i.e. last 7 days until yesterday is equivalent to LAST_7_DAYS
    start <- gsub("-","",format(Sys.Date()-7,"%Y-%m-%d")) #start 7 days ago
    end <- gsub("-","",format(Sys.Date()-1,"%Y-%m-%d")) #until yesterday

    #pull AdWords data
    body <- statement(select=c('Date', 'Device','ConversionValue', 'Cost', 'ConvertedClicks', 'Clicks'),
    report="ACCOUNT_PERFORMANCE_REPORT", start=start, end=end)
    data <- getData(clientCustomerId='xxx-xxx-xxxx', google_auth=google_auth ,statement=body)

**Comment by jburkhardt** [comment]
Thanks! I will look at your issue soon.

**Comment by D-sizzle** [comment]
Thanks! This now works.
