### ISSUE TITLE
R 3.1.3 dependency

### ISSUE THREAD

**Issue by daroczig** [jburkhardt/RAdwords#17]
Sorry for the lame question, but can you please let me know why depending on R 3.1.3? I am a happy user of  R 3.1.2 and have not seen any issues with the package.

**Comment by mbannert** [comment]
@jburkhardt guess he's right. I don't see we're going to fix it on CRAN until the next release, but we could downgrade to 3.0.0 on github. Do you see any issues?

**Comment by jburkhardt** [comment]
The package hosted on github now depends on R >= 3.0.0. Just reinstall the package from the github repository.

**Comment by daroczig** [comment]
Thanks a lot, now I can delete my fork with that only one commit at https://github.com/daroczig/RAdwords/commit/55037e0e03773f961903b6519d6f4687cc5e2fe2 :) Much appreciated, and keep up the great work with this really useful package.
