### ISSUE TITLE
Pulling QS from CRITERIA_PERFORMANCE_REPORT

### ISSUE THREAD

**Issue by D-sizzle** [jburkhardt/RAdwords#19]
Im just trying to pull quality score data at at the account or campaign level. Unfortunatley even without selecting, it parses by day or keyword. Something makes the request a lot longer than it needs to be....

    body <- statement(select=c('AccountDescriptiveName', 'CampaignName',  'QualityScore', 'Clicks' ),
    report="CRITERIA_PERFORMANCE_REPORT", start=start, end=end)
    data <- getData(clientCustomerId='xxx-xxx-xxxx', google_auth=google_auth ,statement=body)

**Comment by jburkhardt** [comment]
There is simple reason for that. The Quality Score is a metric which is only available on keyword level. An aggregated calculation of the QS for Campaigns or Account does not exist. Thus selecting 'QualityScore' in the statment always returns a dataframe with data for each keyword in the account.
