### ISSUE TITLE
Can't download data

### ISSUE THREAD

**Issue by tokumotion** [jburkhardt/RAdwords#23]
I'm getting this error after I authenticate with Google API and AdWords Developer Token.

Do you know how can I fix this issue?

> data <- getData(clientCustomerId = *****, google_auth = Adwords, 
>+                        statement = report)
>*   Trying 64.233.177.113...
>* Connected to adwords.google.com (64.233.177.113) port 443 (#0)
>* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
>* Server certificate: adwords.google.com
>* Server certificate: Google Internet Authority G2
>* Server certificate: GeoTrust Global CA
>* Server certificate: Equifax Secure Certificate Authority
>POST /api/adwords/reportdownload/v201506 HTTP/1.1
>Host: adwords.google.com
>Accept: */*
>Authorization: Bearer *****************
>developerToken: ***************
>clientCustomerId: ***************
>Content-Length: 358
>Content-Type: application/x-www-form-urlencoded

>* upload completely sent off: 358 out of 358 bytes
>< HTTP/1.1 400 Bad Request
>< Content-Type: text/xml
>< Date: Sun, 27 Sep 2015 23:07:20 GMT
>< Expires: Sun, 27 Sep 2015 23:07:20 GMT
>< Cache-Control: private, max-age=0
>< X-Content-Type-Options: nosniff
>< X-Frame-Options: SAMEORIGIN
>< X-XSS-Protection: 1; mode=block
>< Server: GSE
>< Accept-Ranges: none
>< Vary: Accept-Encoding
>< Transfer-Encoding: chunked
>< 
>* Connection #0 to host adwords.google.com left intact
>Error in `[.default`(xj, i) : 
 > only 0's may be mixed with negative subscripts

**Comment by tokumotion** [comment]
I found my error. Thank you!

**Comment by Varshul** [comment]
Hey can you tell us what the issue is as I am facing the same error ?

**Comment by jburkhardt** [comment]
I guess you use the MCC ID in `getData()` by mistake. Take the Account ID in `getData()` instead.

**Comment by Varshul** [comment]
No that was not the case. There was a slight change in Adwords API, which somehow I was not aware of.

**Comment by smhmic** [comment]
I am having the same issue, on a script which was previously running without issue.  I am using the proper account id, not an MCC id.  How can I resolve this error?

**Comment by jburkhardt** [comment]
Please provide
- statement, R code
- OS
- R Version
- RAdwords version

**Comment by smhmic** [comment]
RAdwords version 0.1.6
R version 3.2.1 (2015-06-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

Statement:
```
body <- RAdwords::statement(select = c("KeywordText", "KeywordMatchType",
        "CampaignName", "Date", "AdGroupName", "AdGroupStatus",
        "Impressions", "Clicks", "Conversions", "Ctr", "AverageCpc",
        "Cost", "AveragePosition"), report = "KEYWORDS_PERFORMANCE_REPORT",
        start = start.charint, end = end.charint)
ppc.data <- RAdwords::getData(client.id, tokens, body)
```
Traceback:
```
10: NextMethod("[")
9: `[.factor`(xj, i)
8: xj[i]
7: `[.data.frame`(data, 2:(nrow(data) - 1), 1)
6: data[2:(nrow(data) - 1), 1]
5: as.data.frame(data[2:(nrow(data) - 1), 1])
4: transformData(data, report = attributes(statement)$reportType, 
       apiVersion = apiVersion)
3: RAdwords::getData(client.id, tokens, body) at <tmp>#18
```

**Comment by jburkhardt** [comment]
Please update to RAdwords 0.1.7. This makes sure you are running on the latest Adwords API version.
```
require(devtools)
install_github('jburkhardt/RAdwords')
```
Since the API version v201506 Google renamed a view attributes. "KeywordText" is no longer valid. Instead use "Criteria".
Always be aware of the API version you are running on. RAdwords 0.1.7 runs on v201509. It might be worth to have a look at the migration guides:
https://developers.google.com/adwords/api/docs/guides/migration/v201506
https://developers.google.com/adwords/api/docs/guides/migration/v201509

Moreover you can see the available metrics and naming convention for each report with ```metrics()```. In your case:
```
metrics(""KEYWORDS_PERFORMANCE_REPORT"")
```

**Comment by NabeelahB** [comment]
I get the same error. I have specified the correct clientid and not the MCC id. How to solve the same?
`body <- statement(select=c('Cost'),
                  report="ACCOUNT_PERFORMANCE_REPORT",
                  start="20150320",
                  end="20160321")

data <- getData(clientCustomerId='id', google_auth=google_auth ,statement=body)

Content-Type: application/x-www-form-urlencoded

* upload completely sent off: 88 out of 88 bytes
< HTTP/1.1 400 Bad Request
< Content-Type: text/xml
< Date: Tue, 03 May 2016 07:46:35 GMT
< Expires: Tue, 03 May 2016 07:46:35 GMT
< Cache-Control: private, max-age=0
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< Server: GSE
< Accept-Ranges: none
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< 
* Connection #0 to host adwords.google.com left intact
Error in `[.default`(xj, i) : 
  only 0's may be mixed with negative subscripts`

**Comment by jburkhardt** [comment]
Please make sure you run with the latest RAdwords version before you report any issues.  Install from the github repository!  

Please provide the following information along with the issue:

- Operating System
- R Version
- RAdwords version

**Comment by NabeelahB** [comment]
The issue resolved after updating the package. Thanks :)

**Comment by jburkhardt** [comment]
Good.
