### ISSUE TITLE
How can i call loadToken function directly

### ISSUE THREAD

**Issue by 123saga** [jburkhardt/RAdwords#25]
Hi, I would like to re-use the authentication(client id,secrete, refresh token) details and pass them to loadToken function. Is there any way I can do that.

**Comment by jburkhardt** [comment]
Hi,
why do you want do that? I think there is no need for this task: doAuth() manages the whole authentication process and you can save the credentials into an R object. This object you can use in later instances if your access token is expired and there ist no need to re-authenticate from scratch. getData() automatically refreshes the token if expired. If you want to refreh the token have a look into refrehToken().

For your info:
loadToken only works one time per authentication process. Due to Adwords API regulations you only can retrieve the access token one time. Once you have done this you cannot use loadToken() again. The access token you received in the initial auth process will be refreshed if expired within getData().

Read the loadToken function description:
loadToken loads the access token using credentials provided by getAuth. Execution of function is possible only once per authentication process. Usually you need not to run loadToken() explicitly since the whole authentication process is managed by doAuth.

**Comment by 123saga** [comment]
Hi, Thanks for your response, I wanted to run a script across multiple account based on the input, in this case, I guess onetime load might not help me. I have to do authenticate every time, I cannot automate. At least I am looking for way to save the R Object with specific name, so that I can reuse.
Does it make sense, once again thanks for your help. please let me know if I am  missing anything here.

**Comment by jburkhardt** [comment]
If you want to pull data from multiple accounts, then best practice is to collect all accounts within one MCC. This provided, you authenticate your Adwords MCC once and simply query the accounts one after another with a loop. There is no extra authentication necesarry for each account.
Here is an example:

```
# authentication, once done you can access all accounts in your MCC
google_auth <- doAuth()
# specify date range, i.e. last two weeks until yesterday
yesterday <- gsub("-","",format(Sys.Date()-1,"%Y-%m-%d"))
twoWeeks <- gsub("-","",format(Sys.Date()-14,"%Y-%m-%d"))
# create statement
body <- statement(select=c('Date','AccountDescriptiveName','CampaignName','Impressions','Clicks','Cost','Conversions'),
                  report="CAMPAIGN_PERFORMANCE_REPORT",
                  start=twoWeeks,
                  end=yesterday)
# vector of account IDs
accounts <- c("xxx-xxx-xxxx",#Account 1
              "xxx-xxx-xxxx",#Account 2
              "xxx-xxx-xxxx")#Account 3
# loop over accounts and rbind data to dataframe
dataList <- list()
for(account in accounts){
  dataList[[account]] <- getData(clientCustomerId=account,statement=body,google_auth = google_auth)
}
# bind list to dataframe
data <- do.call(rbind, dataList)
```
Does this help?

**Comment by 123saga** [comment]
Hi Johannes, thanks, looks like this solve the problem if the accounts are under in one MCC, but i might need to deal with accounts under multiple MCC.

**Comment by jburkhardt** [comment]
Multiple MCC Accounts make life more complicated. Especially because it is so easy to link different accounts to one MCC.
However you could try to do following:
```
#set save=F in doAuth() and assign credentials for each MCC in seperate R objects. This prevents R to save .google.auth.RData on your local disk. Instead save credentials only in R object
credentialsMCC1 <- doAuth(save=F)
credentialsMCC2 <- doAuth(save=F)
#your query
body <- statement(...)
#load data
dataMCC1 <- getData(clientCustomerId="***-***-****", google_auth=credentialsMCC1, statement=body)
dataMCC2 <- getData(clientCustomerId="***-***-****", google_auth=credentialsMCC2, statement=body)
```
Does this work for you?

**Comment by 123saga** [comment]
Yeah,I was thinking the same but want to eliminate command line interface inputs everytime I run analysis it would be great to save the files but with different names for reuse.

**Comment by jburkhardt** [comment]
Why don´t you save the credential objects within a RData  file which you can simply load into the R session of your automated task.
Authentication script which you only execute once:
```
#set save=F in doAuth() and assign credentials for each MCC in seperate R objects. This prevents R to save .google.auth.RData on your local disk. Instead save credentials only in R object
credentialsMCC1 <- doAuth(save=F)
credentialsMCC2 <- doAuth(save=F)
#save objects
save(credentialsMCC1, credentialsMCC2, file="/...your directory.../credentials.RData")
```
Production script which you can execute automatically:
```
#load credential objects
load( file="/...your directory.../credentials.RData")
#your query
body <- statement(...)
#load data
dataMCC1 <- getData(clientCustomerId="***-***-****", google_auth=credentialsMCC1, statement=body)
dataMCC2 <- getData(clientCustomerId="***-***-****", google_auth=credentialsMCC2, statement=body)
```

**Comment by 123saga** [comment]
Perfect! thank you
