### ISSUE TITLE
v201506 5 October 2015 11 April 2016 Migrate to v201509 

### ISSUE THREAD

**Issue by dcabanillas** [jburkhardt/RAdwords#26]
The current API is deprecated.

**Comment by jburkhardt** [comment]
Take a look at the RAdwords Version v.0.1.7:
https://github.com/jburkhardt/RAdwords/releases
Migration towards v201509 is already done!
Although v201506 is deprecated, the API version v201506 is still functioning until the sunset date 11.04.2016.
