### ISSUE TITLE
Video Performance Report

### ISSUE THREAD

**Issue by tokumotion** [jburkhardt/RAdwords#30]
Hi,

Wondering if we could have this report as part of the package's options.

Documentation here: https://developers.google.com/adwords/api/docs/appendix/reports/video-performance-report

**Comment by jburkhardt** [comment]
Thanks for the note! I will look into it soon...

**Comment by jburkhardt** [comment]
@tokumotion Could you please test again? I fixed the function ```reports()```. Please reinstall RAdwords from my github repository and make sure you use version 0.1.7 with apiVersion set to "201509". Thanks!

**Comment by tokumotion** [comment]
@jburkhardt it worked! Thank you!
