### ISSUE TITLE
Worrying problem in Shopping Campaigns reports

### ISSUE THREAD

**Issue by djuery** [jburkhardt/RAdwords#31]
Hi @jburkhardt, @mbannert, and first of all many thanks for this incredible RAdwords package.

I noticed a very disturbing bug in the transformData.R file. The problem is impacted by this part of code:
```
else if (ncol(data) > 1) {
        data <- data[-1, ]
        data <- data[-nrow(data), ]
    }
```

The `data <- data[-nrow(data), ]` code should be, as expected, removing the Total lines from the data.frame, which is a good thing.
However, I noticed that when using a PRODUCT_PARTITION_REPORT, the last line isn't at all the Total line but a real partition line. `data <- data[-nrow(data), ]` is thus removing a real report line, which may have serious consequences on the result, especially when working with RoI or cost data.

My suggestion is therefore to change:
```
data <- data[-nrow(data), ]
```

with
```
if(reportType != "PRODUCT_PARTITION_REPORT") {
  data <- data[-nrow(data), ]
}
```

or even
```
if(data[nrow(data), 1] == "Total") {
  data <- data[-nrow(data), ]
}
```

to ensure this works for every non-total-like report, if you see what I mean.

Many thanks in advance!

Damien

**Comment by jburkhardt** [comment]
Hi Damien,
thanks for the note and the solution to the problem.
Yet I never used the PRODUCT_PARTITION_REPORT, thus didn´t notice the behaviour.
I will implemet your solution.
Kind regards,
Johannes

**Comment by jburkhardt** [comment]
The Bug should be fixed now. Could you please reinstall the package from the github repository and test if the report is fine?

**Comment by djuery** [comment]
Hi @jburkhardt,

many thanks for your prompt reply! Indeed, everything is just working fine now.
I'll just open here an issue whenever there are issues with other report types (the SHOPPING_PERFORMANCE_REPORT maybe).
