### ISSUE TITLE
Shopping campaign reports and zero impressions

### ISSUE THREAD

**Issue by djuery** [jburkhardt/RAdwords#32]
Hi @jburkhardt,

further to my previous issue, I noticed another problem when querying Shopping Campaign reports (like *PRODUCT_PARTITION_REPORT* or *SHOPPING_PERFORMANCE_REPORT*) with Zero Impressions.

Normally, when you use *getData* to download the data from Google AdWords, you include the parameter `where = "Impressions >= 0"` into the `statement` function if you want the AWQL predicate to include Zero Impressions. However, for some reason, this is with zero effect for these Shopping Campaign reports.

The only way of doing it is to force the parameter directly into the `httpheader` from *RCurl::getURL* function. In other terms, one has to write the `httpheader` like this:
```
httpheader = c(Authorization = google.auth,
    developerToken = credlist$auth.developerToken,
    clientCustomerId = clientCustomerId,
    includeZeroImpressions = TRUE)
```

Please find below the exact reference (AdWords API Dev Doc):
https://developers.google.com/adwords/api/docs/guides/zero-impression-reports#explicitly_including_zero_impressions

Therefore, my suggestion is to add a parameter into the *getData* function, that could be called *forceZeroImpressions*, and re-write the whole file getData.R as follows:
```
function (clientCustomerId, google_auth, statement, apiVersion = "201509", 
    transformation = TRUE, changeNames = TRUE, forceZeroImpressions = FALSE, verbose = FALSE) 
{
    access <- google_auth$access
    credlist <- google_auth$credentials
    if (as.numeric(Sys.time()) - 3600 >= access$timeStamp) {
        access <- refreshToken(google_auth)
    }
    google.auth <- paste(access$token_type, access$access_token)
    cert <- system.file("CurlSSL", "ca-bundle.crt", package = "RCurl")

    if (forceZeroImpressions == TRUE) {
      data <- RCurl::getURL(paste("https://adwords.google.com/api/adwords/reportdownload/v", 
          apiVersion, sep = ""), httpheader = c(Authorization = google.auth, 
          developerToken = credlist$auth.developerToken, clientCustomerId = clientCustomerId, includeZeroImpressions = TRUE), 
          postfields = statement, verbose = verbose, cainfo = cert, 
          ssl.verifypeer = TRUE)
    } else {
      data <- RCurl::getURL(paste("https://adwords.google.com/api/adwords/reportdownload/v", 
          apiVersion, sep = ""), httpheader = c(Authorization = google.auth, 
          developerToken = credlist$auth.developerToken, clientCustomerId = clientCustomerId), 
          postfields = statement, verbose = verbose, cainfo = cert, 
          ssl.verifypeer = TRUE)
    }

    if (transformation == TRUE) {
        data <- transformData(data, report = attributes(statement)$reportType, 
            apiVersion = apiVersion)
        if (changeNames == TRUE) {
            data <- changeNames(data)
        }
    }
    data
}
```

Many thanks for taking this into consideration, as this will certainly improve the package!

Cheers,
Damien

**Comment by jburkhardt** [comment]
Thank for your message! By default zero impressions are included in all reports. This is the reason why there is no difference between including ```where = "Impressions >= 0```in ```statement()``` or not.
If you want to exclude zero impressions just go with '''where = "Impressions > 0'''.
This should make the adjustments in the httpheader obsolete and keep things simpler.

**Comment by djuery** [comment]
I agree that by default, zero impressions **should be** included in all reports. However, I can assure you that this is not the case at all when you deal with PRODUCT_PARTITION_REPORT.
Whether I use `where = "Impressions > 0` or `where = "Impressions >= 0`, the results are the same, even if they shouldn't be.
That's why I suggested to add a *forcing parameter* in order to really get zero impressions with shopping campaign reports.
Cheers!

**Comment by jburkhardt** [comment]
Ok - I can see you your point. Either way it may be a good idea to set zero impressions explicitly. I will incorporate your suggestions! Thanks!

**Comment by djuery** [comment]
Perfect! You just hit the nail on the head!

**Comment by jburkhardt** [comment]
Could you please test if your queried data are correct now?

**Comment by djuery** [comment]
Working perfectly, many thanks! Therefore, people can choose whether to include zero impressions or not explicitly, depending on the report they use and its allowance.
Thanks!

**Comment by braggbear** [comment]
How can one explicitly determine that they want zero impressions or don't want zero impressions?  Where in the code should i put this?  Could someone please provide an example?  Thanks!

**Comment by jburkhardt** [comment]
@braggbear 
Within the function ```getData()```simply set the argument ```includeZeroImpressions```to ```TRUE```.
```R
data <- getData(clientCustomerId='xxx-xxx-xxxx',
                           google_auth=google_auth,
                          statement=body,
                          includeZeroImpressions=TRUE)
```
Hope that helps!
