### ISSUE TITLE
Shopping performance report issue

### ISSUE THREAD

**Issue by djuery** [jburkhardt/RAdwords#33]
Hi @jburkhardt,

hope you're well.

As I feared in my previous messages, I just wanted to inform you that the `SHOPPING_PERFORMANCE_REPORT` does not have a total line at the bottom of the report, meaning that again there is an issue in the `transformData` file because it will purely remove a real report line.

My solution is therefore to change:
```
if (report != "PRODUCT_PARTITION_REPORT") {
  data <- data[-nrow(data), ]
}
```
line in it with:
```
if(report != "PRODUCT_PARTITION_REPORT" & report != "SHOPPING_PERFORMANCE_REPORT") {
  data <- data[-nrow(data), ]
}
```

However, I maintain that this replacement:
```
if(data[nrow(data), 1] == "Total") {
  data <- data[-nrow(data), ]
}
```
is preferred, as it would ensure that the fix works for every report type whose last line is not a Total line.

Many thanks for the implementation!

Cheers,
Damien

**Comment by jburkhardt** [comment]
Hi @djuery,
thanks again for your contribution!
I implemented the latter code as you suggested. Could you please test if the ```PRODUCT_PARTITION_REPORT``` and ```SHOPPING_PERFORMANCE_REPORT``` are fine?
Regards,
Johannes

**Comment by djuery** [comment]
@jburkhardt,

I just allowed myself to debug the whole `transformData` file thanks to some testing routines I have been writing specifically to compare the raw API reports' data to the data transformed by the parameter `transformation = TRUE`.

In the following, I am only talking about the `transformData.R` file.

Because of this line:
```
else if (ncol(data) > 1) {
        data <- data[-1, ]
        if (data[nrow(data), 1] == "Total") {
            data <- data[-nrow(data), ]
        }
    }
```

the file is doing well for queried data with more than one column. However, for queried data that contains only one column (`PRODUCT_PARTITION_REPORT` with only `ProductGroup` for example), the issue is not implemented because this part of code isn't changed:
```
if (ncol(data) == 1) {
        variableName <- names(data)
        data <- as.data.frame(data[2:(nrow(data) - 1), 1])
        names(data) <- variableName
    }
```

Therefore, in order to resolve definitely these issues with the Total line, I'd suggest to change the last part above:
```
if (ncol(data) == 1) {
        variableName <- names(data)
        if (data[nrow(data), 1] == "Total") {
          data <- as.data.frame(data[2:(nrow(data) - 1), 1])
        } else {
          data <- as.data.frame(data[2:nrow(data), 1])
        }
        names(data) <- variableName
    }
```

Regards,
Damien

**Comment by jburkhardt** [comment]
Should be fine now!
