### ISSUE TITLE
How to reset the doAuth()

### ISSUE THREAD

**Issue by maaraaj** [jburkhardt/RAdwords#34]
I want to change my client ID, Secret ...provided in the first authentication

**Comment by jburkhardt** [comment]
Just delete the file ```.google.auth.RData``` in the working directory of your R project.

**Comment by mbannert** [comment]
You can do it from within R, which might be the easiest way if you're not familiar with hidden files. 
`system("rm .google.auth.RData")`

**Comment by maaraaj** [comment]
Got it ..Thanks Guys !!
