### ISSUE TITLE
Error in `[.default`(xj, i) : 

### ISSUE THREAD

**Issue by eliasdabbas** [jburkhardt/RAdwords#36]
"only 0's may be mixed with negative subscripts"

I'm getting the above messages after successfully authenticating and running the same query you have in the example. 

body <- statement(select=c('Clicks','AveragePosition','Cost','Ctr'),
                  report="ACCOUNT_PERFORMANCE_REPORT",
                  start="2014-03-20",
                  end="2014-03-21")
google_auth <- doAuth()
getData(clientCustomerId = "my-client's-id", google_auth = google_auth, statement = body)

RAdwords Package Version: 0.1.7
MacOSX El Capitan 
RStudio version: 0.99.875 (had the same issue in the previous version as well)

Can you please check or let me know if I'm missing something? 

Thanks a lot!

**Comment by tokumotion** [comment]
Hi, have you checked if those variable names conform with the new AdWords API? Example might be outdated.
Check here: https://developers.google.com/adwords/api/docs/reference/#v201502

**Comment by eliasdabbas** [comment]
Thanks. 
I guess so. I tried again several times. I added 'transformation = TRUE' to make sure the format works in R. I changed parameters, I also tried explicitly specifying the API versions, and in all cases I'm getting the same error message. 

I just tried an example statement from the Adwords page itself: 
__rdquery=SELECT+Criteria+FROM+KEYWORDS_PERFORMANCE_REPORT+DURING+20150101,20150325&__fmt=CSV

from this page: 
https://developers.google.com/adwords/api/docs/guides/awql?hl=en

Still the same message. It seems there is some problem in the logic of the statement. 
Not sure what's going wrong. 
Thanks, 
Elias

**Comment by tokumotion** [comment]
@eliasdabbas: 

- do you have a Google AdWords API account?
- do you have the last dev version of the package?

**Comment by jburkhardt** [comment]
Hi @eliasdabbas,
I guess this is a simple syntax error in your statement. Please have a second look at your statement again. Your format of the date is not supported by the API. Please use ```"20140320"``` instead.
The example of the package documentation is correct and different from your example.
```
body <- statement(select=c('Clicks','AveragePosition','Cost','Ctr'),
                  report="ACCOUNT_PERFORMANCE_REPORT",
                  start="20140320",
                  end="20140321")
```
hth

**Comment by jburkhardt** [comment]
Update:
I made an adjustment in the ```statement()``` function. Now you should be able to use both ```"20140320"``` and ```"2014-03-20"```. Please update the package from the github repository.
@eliasdabbas Does it work for you?

**Comment by eliasdabbas** [comment]
Thanks. Just downloaded and tried it, now I'm getting a 'developer token not approved' error message: 

"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><reportDownloadError><ApiError><type>QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED</type><trigger>&lt;null&gt;</trigger><fieldPath></fieldPath></ApiError></reportDownloadError>"

@tokumotion I have an API account with  "Test Accounts" access. Could be the issue. I'll check with Google.

**Comment by mbannert** [comment]
If you have a test account it *definitely* ain't working. Hold on folks, we'll come up with an FAQ soon. @jburkhardt let's do this.
