### ISSUE TITLE
Always Get Bad Request since last update

### ISSUE THREAD

**Issue by ppbergeron** [jburkhardt/RAdwords#37]
Hi, i've forked and used this awesome code for a while.

I dont understand exactly why, but something hapened and now I always get an Error: Bad request when i query the API, including when i am using your example code.

![image](https://cloud.githubusercontent.com/assets/11300236/13225607/8af66dd6-d95b-11e5-975b-ce418ce76302.png)

Any clues?

**Comment by tokumotion** [comment]
Do you have an AdWords Developer Token?

**Comment by ppbergeron** [comment]
Yes, I used the code in the past and had no issues.

I'm actually testing older version of the same code and other forks i sent
to colleagues to see if it's on my side.

But i've looked at my OAuth and erverything seems fine there.

2016-02-22 13:39 GMT-05:00 Miguel Tokuoto <notifications@github.com>:

**Comment by ppbergeron** [comment]
OK. Sorry, SO VERY sorry.

I've tested the exact same code on another computer and it worked. So it's
something local.

My bad,

#Resolved

2016-02-22 13:41 GMT-05:00 Pascal-philippe Bergeron <pp.bergeron@gmail.com>:
