### ISSUE TITLE
How change auth.developerToken at doAuth()?

### ISSUE THREAD

**Issue by selesnow** [jburkhardt/RAdwords#39]
I need change auth.developerToken, but i cant do this because doAuth return my first credentials list, pleas say how i can repeatedly authentication?

**Comment by jburkhardt** [comment]
Hi,
probably the easiest way is to delete the old credentials and start a new authentication process.

Delete the file .google.auth.RData in the current working directory or run wihtin your R session:
```
#within R run:
system("rm .google.auth.RData")
```
Start a new authentication process
```
#remove auth objects in running R session
rm(google_auth) #or any corresponding R objects
#start authentication
google_auth <- doAuth()
```
Hope that helps,
Johannes

**Comment by selesnow** [comment]
Thanks, it work.
