### ISSUE TITLE
get keywords

### ISSUE THREAD

**Issue by dcabanillas** [jburkhardt/RAdwords#40]
With the api 201601

Sending the requeset
query_conversion <- statement(select=c('KeywordText','Clicks','Cost','Ctr'),
                                report="KEYWORDS_PERFORMANCE_REPORT",
                                start=begin_data,
                                end=end_data)
  
  #https://github.com/jburkhardt/RAdwords/issues/25
  data_conversion <- getData(clientCustomerId=account, google_auth=google_auth ,statement=query_conversion)
  

I'm getting the following error. I think that the problem is KeywordText

"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><reportDownloadError><ApiError><type>ReportDefinitionError.INVALID_FIELD_NAME_FOR_REPORT</type><trigger></trigger><fieldPath>KeywordText</fieldPath></ApiError></reportDownloadError>"
1
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><repo

**Comment by jburkhardt** [comment]
You are using the wrong attribute! Google changed some of the attribute names in the latest API version.
Try ```Criteria``` instead of ```KeywordText```.
Hope that helps!
