### ISSUE TITLE
Does not work correctly with the Cyrillic alphabet

### ISSUE THREAD

**Issue by selesnow** [jburkhardt/RAdwords#41]
Hello.
Faced with the fact that does not work correctly with the Cyrillic alphabet, if returned value contains Cirillic letter "я" or "Я" API request is break and returned truncate result.

For Example:

<img class="http://picsee.net/upload/2016-04-04/6d34c8b09c7e.jpg" src="http://picsee.net/upload/2016-04-04/6d34c8b09c7e.jpg" >
http://picsee.net/upload/2016-04-04/6d34c8b09c7e.jpg

**Comment by jburkhardt** [comment]
Could you please post the error message from thr R console?

**Comment by selesnow** [comment]
<img src="http://picsee.net/upload/2016-04-04/1bbc018a991b.jpg" data-canonical-src="http://picsee.net/upload/2016-04-04/1bbc018a991b.jpg" style="max-width:100%;">
http://picsee.net/upload/2016-04-04/1bbc018a991b.jpg

Object have only few rows.
<img src="http://picsee.net/upload/2016-04-04/7a990350a051.jpg" data-canonical-src="http://picsee.net/upload/2016-04-04/7a990350a051.jpg" style="max-width:100%;">
http://picsee.net/upload/2016-04-04/7a990350a051.jpg

Object must have 134683 rows, after i change AdGroupName to AdGroupID returns 134683 rows.
<img src="http://picsee.net/upload/2016-04-04/ee3dc0107b1c.jpg" data-canonical-src="http://picsee.net/upload/2016-04-04/ee3dc0107b1c.jpg" style="max-width:100%;">
http://picsee.net/upload/2016-04-04/ee3dc0107b1c.jpg

<img src="http://picsee.net/upload/2016-04-04/1ad2f9cad91f.jpg" data-canonical-src="http://picsee.net/upload/2016-04-04/1ad2f9cad91f.jpg" style="max-width:100%;">
http://picsee.net/upload/2016-04-04/1ad2f9cad91f.jpg

If return data have value "Я", or "я" api request is break and return not full data.

**Comment by jburkhardt** [comment]
I suppose the function ```transformData``` causes the problem.
Let´s try to do the following:
```
#create you query as usual
body <- statement(...)
#pull the data without transformation, you get the raw text xml format
dataRaw <- getData(..., transform=F)
# Yet, there should not be any error
#start debug mode for transformData
debug(transformData)
#run transformData on raw data in debug mode
data <- transformData(dataRaw, report = "YOUR_REPORT_TYPE")
#now execute the function stepwise by clicking enter and investigate the error
```
You can quit the debug mode with "Q". 
I hope this leads to any new insights...

**Comment by mbannert** [comment]
Can you run `Sys.getlocale()` in R ? This might be some encoding issue, though I don't know yet whether it's Google's problem, `Radwords'`problem or your OS' problem. You seem to have an english R config though -- as we can see from the error message. Do you use cyrillic letter frequently on your system? Should be covered by UTF-8, isn't it?

**Comment by selesnow** [comment]
Hello mbannert 

> Sys.getlocale()
[1] "LC_COLLATE=Russian_Russia.1251;LC_CTYPE=Russian_Russia.1251;LC_MONETARY=Russian_Russia.1251;LC_NUMERIC=C;LC_TIME=Russian_Russia.1251"

Do you use cyrillic letter frequently on your system?
Yes, my location CIS and all adwords project constain cyrillic letter keywords.

**Comment by selesnow** [comment]
strange that the only problem with the letter "я", other cyrillic letters not break the script.

**Comment by selesnow** [comment]
#create you query as usual
body <- statement(...)
#pull the data without transformation, you get the raw text xml format
dataRaw <- getData(..., transform=F)
# Yet, there should not be any error
#start debug mode for transformData
debug(transformData)
#run transformData on raw data in debug mode
data <- transformData(dataRaw, report = "YOUR_REPORT_TYPE")
#now execute the function stepwise by clicking enter and investigate the error

Return this:

`
> debug(transformData)
> dataRaw1 <- transformData(dataRaw, report = "KEYWORDS_PERFORMANCE_REPORT", apiVersion = "201509" )
debugging in: transformData(dataRaw, report = "KEYWORDS_PERFORMANCE_REPORT", 
    apiVersion = "201509")
debug: {
    data <- read.csv2(textConnection(data), sep = ",", header = F)[-1, 
        ]
    data <- as.data.frame(data)
    for (i in 1:ncol(data)) {
        names(data)[i] <- as.character(data[1, i])
    }
    if (ncol(data) == 1) {
        variableName <- names(data)
        if (nrow(data) > 0) {
            if (data[nrow(data), 1] == "Total") {
                data <- as.data.frame(data[2:(nrow(data) - 1), 
                  1])
            }
            else {
                data <- as.data.frame(data[2:nrow(data), 1])
            }
        }
        names(data) <- variableName
    }
    else if (ncol(data) > 1) {
        data <- data[-1, ]
        if (nrow(data) > 0) {
            if (data[nrow(data), 1] == "Total") {
                data <- data[-nrow(data), ]
            }
        }
    }
    if ("Day" %in% colnames(data)) {
        data$Day <- as.Date(data$Day)
    }
    report <- gsub("_", "-", report)
    report <- tolower(report)
    switch(apiVersion, `201601` = reportType <- read.csv(paste(system.file(package = "RAdwords"), 
        "/extdata/api201601/", report, ".csv", sep = ""), sep = ",", 
        encoding = "UTF-8"), `201509` = reportType <- read.csv(paste(system.file(package = "RAdwords"), 
        "/extdata/api201509/", report, ".csv", sep = ""), sep = ",", 
        encoding = "UTF-8"), `201506` = reportType <- read.csv(paste(system.file(package = "RAdwords"), 
        "/extdata/api201506/", report, ".csv", sep = ""), sep = ",", 
        encoding = "UTF-8"))
    i <- sapply(data, is.factor)
    data[i] <- lapply(data[i], as.character)
    Type <- NULL
    doubleVar <- as.character(subset(reportType, Type == "Double")$Display.Name)
    perVar <- as.numeric(grep("%", data))
    perVar <- names(data)[perVar]
    for (var in doubleVar) {
        if (var %in% colnames(data) && var %in% perVar) {
            data[, var] <- sub("%", "", data[, var])
            data[, var] <- as.numeric(data[, var])/100
        }
    }
    Behavior = NULL
    metricVar <- as.character(subset(reportType, Behavior == 
        "Metric")$Display.Name)
    for (var in metricVar) {
        if (var %in% colnames(data)) {
            data[, var] <- as.character(data[, var])
            data[, var] <- sub(",", "", data[, var])
            data[, var] <- as.numeric(data[, var])
        }
    }
    Type <- NULL
    monetaryVar <- as.character(subset(reportType, Type == "Money")$Display.Name)
    for (var in monetaryVar) {
        if (var %in% colnames(data)) {
            data[, var] <- as.character(data[, var])
            data[, var] <- suppressWarnings(as.numeric(data[, 
                var]))
            data[, var] <- data[, var]/1e+06
        }
    }
    names(data) <- gsub(" ", "", names(data))
    data
}
Browse[2]> c
exiting from: transformData(dataRaw, report = "KEYWORDS_PERFORMANCE_REPORT", 
    apiVersion = "201509")
Warning message:
NAs introduced by coercion 
`

But again returnn only 13 rows.
<img src="http://picsee.net/upload/2016-04-04/95cf46b67041.jpg" data-canonical-src="http://picsee.net/upload/2016-04-04/95cf46b67041.jpg" style="max-width:100%;">
http://picsee.net/upload/2016-04-04/95cf46b67041.jpg

**Comment by selesnow** [comment]
At this step we have truncate data frame.
<img src="http://picsee.net/upload/2016-04-04/2e4dcac4e8f2.jpg" data-canonical-src="http://picsee.net/upload/2016-04-04/2e4dcac4e8f2.jpg" style="max-width:100%;">
http://picsee.net/upload/2016-04-04/2e4dcac4e8f2.jpg

**Comment by mbannert** [comment]
Hmm, looks like the cyrillic letter introduces delimiter problem. Or maybe it's not even the letter (Capital YA) but some other delimiter problem. Often single or double quotes cause trouble. However there seems to be mixed config on your machine. It says Russian, but the error messages in your screenshots are english. 

However, you definitely don't use UTF-8 or UTF-16 encoding but some location specific encoding. 
Try to set it to UTF-8. Maybe it helps. Don't have a lot of experience with cyrillic letters though. Tested it:  my english UTF-8 locale did not have any troubles with the cyrillic YA.

**Comment by selesnow** [comment]
> Try to set it to UTF-8.

How i can do this?

**I would like to draw your attention to the fact that the package RGoogleAnalytics is no such problem, maybe it will help you find the answer.**

**Comment by mbannert** [comment]
Dunno about the correct specification for Russian locales. maybe   `?Sys.setlocale` helps.

**Comment by selesnow** [comment]
Function GetReportData from RGoogleAnalytics packege correctly work with  cyrillic letter.

`function (query.builder, token, split_daywise = FALSE, paginate_query = FALSE) 
{
    kMaxDefaultRows <- get("kMaxDefaultRows", envir = rga.environment)
    query.uri <- NULL
    dataframe.param <- data.frame()
    options(RCurlOptions = list(capath = system.file("CurlSSL", 
        "cacert.pem", package = "RCurl"), ssl.verifypeer = FALSE))
    query.builder$SetQueryParams()
    max.rows <- query.builder$max.results()
    if (split_daywise != T && paginate_query != T) {
        query.uri <- ToUri(query.builder, token)
        ga.list <- GetDataFeed(query.uri)
        total.results <- ga.list$totalResults
        items.per.page <- ga.list$itemsPerPage
        contains.sampled.data <- ga.list$containsSampledData
        response.size <- length(ga.list$rows)
        if (total.results < kMaxDefaultRows) {
            max.rows <- kMaxDefaultRows
        }
        if (length(query.builder$dimensions()) == 0) {
            totalrows <- 1
            dataframe.param <- ga.list$rows[[1]]
            dim(dataframe.param) <- c(1, length(dataframe.param))
        }
        else {
            totalrows <- nrow(do.call(rbind, as.list(ga.list$rows)))
            dataframe.param <- rbind(dataframe.param, do.call(rbind, 
                as.list(ga.list$rows)))
        }
        final.df <- SetDataFrame(ga.list$columnHeaders, dataframe.param)
        if (length(ga.list$rows) < total.results) {
            cat("Status of Query:\n")
            cat("The API returned", response.size, "results out of", 
                total.results, "results\n")
            cat("In order to get all results, set paginate_query = T in the GetReportData function.\n")
        }
        else {
            cat("Status of Query:\n")
            cat("The API returned", response.size, "results\n")
        }
        if (contains.sampled.data == T) {
            visits.for.sampled.query <- round(100 * (as.integer(ga.list$sampleSize)/as.integer(ga.list$sampleSpace)), 
                2)
            cat("The query response contains sampled data. It is based on ", 
                visits.for.sampled.query, "% of your visits.\n")
            cat("You can split the query day-wise in order to reduce the effect of sampling.\n")
            cat("Set split_daywise = T in the GetReportData function\n")
            cat("Note that split_daywise = T will automatically invoke Pagination in each sub-query\n")
        }
    }
    else if ((split_daywise == T) || (split_daywise == T && paginate_query == 
        T)) {
        if (query.builder$max.results() < kMaxDefaultRows) {
            cat("Setting Max Results to 10000 for efficient Query Utilization\n")
            query.builder$max.results(kMaxDefaultRows)
        }
        GA.DF <- SplitQueryDaywise(query.builder, token)
        final.df <- SetDataFrame(GA.DF$header, GA.DF$data)
        cat("The API returned", nrow(final.df), "results\n")
    }
    else if (paginate_query == T) {
        if (query.builder$max.results() < kMaxDefaultRows) {
            cat("Setting Max Results to 10000 for efficient Query Utilization\n")
            query.builder$max.results(kMaxDefaultRows)
        }
        query.uri <- ToUri(query.builder, token)
        ga.list <- GetDataFeed(query.uri)
        ga.list.df <- data.frame()
        ga.list.df <- rbind(ga.list.df, do.call(rbind, as.list(ga.list$rows)))
        if (length(ga.list$rows) < ga.list$totalResults) {
            number.of.pages <- ceiling(ga.list$totalResults/length(ga.list$rows))
            if (number.of.pages > 100) {
                number.of.pages <- get("kMaxPages", envir = rga.environment)
            }
            paged.query.list <- PaginateQuery(query.builder, 
                number.of.pages, token)
            inter.df <- rbind(ga.list.df, paged.query.list$data)
            final.df <- SetDataFrame(paged.query.list$headers, 
                inter.df)
            cat("The API returned", nrow(final.df), "results\n")
        }
        else {
            stop("Pagination is not required. Set paginate_Query = F and re-run the query\n")
        }
    }
    return(final.df)
}`

**Comment by jburkhardt** [comment]
Could you share the raw data? I would like to reprocude the behaviour.

**Comment by selesnow** [comment]
> Could you share the raw data? I would like to reprocude the behaviour.

of course, you can download xml object which i get function getData with transformation = F.

Link to this file https://drive.google.com/file/d/0B1rgddqnM9XJZG44dnBSYm0tYkk/view?usp=sharing

**Comment by jburkhardt** [comment]
Please save the data object as a .RData file and provide the .RData file.
```
data <- getData(..., transformation = F)
save(data, file=".../rawData.RData")
```

**Comment by selesnow** [comment]
RData file:
https://drive.google.com/file/d/0B1rgddqnM9XJV2luaDFzSXoyeHM/view?usp=sharing

xmlData file:
https://drive.google.com/file/d/0B1rgddqnM9XJSmV0VzlVLW5HU3c/view?usp=sharing

**Comment by selesnow** [comment]
If you have adwords test account you can add letter "я" to any adwords name, campaing, adgroup or keyword and try get this data to R and you will encounter the same problem.

**Comment by mbannert** [comment]
Oh wait.. Did you just say `adwords test account`... ? The API does NOT work with test accounts and consequently `RAdwords` doesn't neither.

**Comment by jburkhardt** [comment]
@selesnow one more thing: before I can investigate your data, what is the report type?

**Comment by selesnow** [comment]
@mbannert , no i use work adwords account, it i say for example, you can add letter "я" at any adwords name in simple work account for try this problem.

**Comment by selesnow** [comment]
@jburkhardt 

> one more thing: before I can investigate your data, what is the report type?

this problem in all report type, at this example i use keyword_performance_report

**Comment by jburkhardt** [comment]
I guess I found the issue. On my system there are no problems with я in string/character variables. However there is a problem with the attribute ```Search Lost IS (rank)```. Some values may contain ">" or "<" (exmaple is "> 90%"). ```transformData``` does not know how to deal with this and produces NAs.
@selesnow Could you run your statement without the attribute ```Search Lost IS (rank)```. Is it working then?

**Comment by jburkhardt** [comment]
By the way, could you please make sure to use the latest RAdwords Version and set the API version to "201601". Thx

**Comment by selesnow** [comment]
I use last RAdwords version from github, and if i run transformData without SearchLostIS(rank) script break if any value contains letter "я", i try run this function with any parametrs.

Any time script return this message:
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  incomplete final line found by readTableHeader on 'data'

> body1 <- statement(select=c('Date',
+                            'Id',
+                            'Criteria',
+                            'Impressions',
+                            'Clicks',
+                            'Cost',
+                            'Ctr',
+                            'QualityScore',
+                            'AveragePosition'
+ ),
+ report="KEYWORDS_PERFORMANCE_REPORT",
+ start=paste0(start_period["year"],start_period["month"],start_period["day"]),
+ end=paste0(end_period["year"],end_period["month"],end_period["day"]))
> dataRaw <- getData(
+   clientCustomerId = "XXX-XXX-XXXX",
+   google_auth = adwords_auth,
+   statement = body1,
+   transformation = F,
+   apiVersion = "201601")
> dataRaw1 <- transformData(dataRaw, report = "KEYWORDS_PERFORMANCE_REPORT", apiVersion = "201601")
> View(dataRaw1)

Return this:
<img src="http://img.netpeak.ua/alsey/145987601502_kiss_166kb.jpg" data-canonical-src="http://img.netpeak.ua/alsey/145987601502_kiss_166kb.jpg" style="max-width:100%;">
http://img.netpeak.ua/alsey/145987601502_kiss_166kb.jpg

**Comment by selesnow** [comment]
My RAdwords version
<img src="http://img.netpeak.ua/alsey/145987654486_kiss_61kb.jpg" data-canonical-src="http://img.netpeak.ua/alsey/145987654486_kiss_61kb.jpg" style="max-width:100%;">
http://img.netpeak.ua/alsey/145987654486_kiss_61kb.jpg

**Comment by jburkhardt** [comment]
OK. This is strange, since I do not get this error message on my system. I can read your rawData without any difficulty. transformData converts the rawData into a data.frame with 9910 rows. The keywords variable contains я as any other letter.

**Comment by selesnow** [comment]
I can try to do something more?

**Comment by jburkhardt** [comment]
can your run:
```
data <- read.csv2(textConnection(rawData, sep = ",", header = F)[-1,]
data <- as.data.frame(data)
```

**Comment by selesnow** [comment]
read.csv2 and read.csv returne only 26 rows, truncate result.

**Comment by selesnow** [comment]
maybe try read.table ?

**Comment by jburkhardt** [comment]
At least we located your problem now. However I still don´t know why there are issues on your system. Unfortunately I cannot reproduce your error.

**Comment by selesnow** [comment]
Run script from another PC, same problem.
<img src="http://picsee.net/upload/2016-04-05/d3847ebef545.png" data-canonical-src="http://picsee.net/upload/2016-04-05/d3847ebef545.png" style="max-width:100%;">
http://picsee.net/upload/2016-04-05/d3847ebef545.png

**Comment by jburkhardt** [comment]
Could you provide us your code? Maybe email or post it here. Make sure to remove the credential information.

**Comment by selesnow** [comment]
ofcause:

```
require("RAdwords")
require("lubridate")

#Reporting dates
date <- as.POSIXlt(Sys.time())

start_period  <- c(day = "01",
                   month = "03", 
                   year = "2016")
end_period    <- c(day = ifelse(nchar(toString(day(date))) == 1, paste0(0,day(date)),toString(day(date))),
                   month = ifelse(nchar(toString(month(date))) == 1, paste0(0,month(date)),toString(month(date))), 
                   year = toString(year(date)))

#AdWords
adwords_auth <- doAuth()

body <- statement(select=c('Date',
                           'Criteria',
                           'Impressions',
                           'Clicks',
                           'Ctr',
                           'QualityScore',
                           'AveragePosition'
),
report="KEYWORDS_PERFORMANCE_REPORT",
start=paste0(start_period["year"],start_period["month"],start_period["day"]),
end=paste0(end_period["year"],end_period["month"],end_period["day"]))

#4.2.3. Отправка запроса в Google AdWords
adwordsData <- getData(
  clientCustomerId = **"XXX-XXX-XXXX"**,
  google_auth = adwords_auth,
  statement = body,
  transformation = F,
  apiVersion = "201601")

data <- transformData(adwordsData, report = "KEYWORDS_PERFORMANCE_REPORT", apiVersion = "201601")

```

**Comment by selesnow** [comment]
When i change read.csv2 to read.table i get error:

`data1 <- read.table(textConnection(adwordsData), sep = ",", header = FALSE)[-1,]`

Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  : 
  line 1 did not have 7 elements

**Comment by selesnow** [comment]
i find one solution, not the best, but it maybe be hint.

```
write.table(adwordsData, file = "adwords.csv")
data <- read.table(file = "adwords.csv", sep = ",", dec = ".", header = T, skip = 2)
```

It return full result with messange:
Warning messages:
1: In scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  :
  EOF within quoted string
2: In scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  :
  number of items read is not a multiple of the number of columns

And returned data have total row, and incorrect format in percent indicators

<img src="http://img.netpeak.ua/alsey/145994367395_kiss_125kb.jpg" data-canonical-src="http://img.netpeak.ua/alsey/145994367395_kiss_125kb.jpg" style="max-width:100%;">
http://img.netpeak.ua/alsey/145994367395_kiss_125kb.jpg

**Comment by selesnow** [comment]
When i get data from csv file by read.csv2 function this problem is not.

`testCsvRead <- read.csv2(file = "mytest.csv",sep = ",", header = F)`

link to this csv file. https://drive.google.com/file/d/0B1rgddqnM9XJUGdiZ21lTENnQVk/view?usp=sharing

Returne result contains Cirillic letter "я".
<img src="http://img.netpeak.ua/alsey/145994659498_kiss_119kb.jpg" data-canonical-src="http://img.netpeak.ua/alsey/145994659498_kiss_119kb.jpg" style="max-width:100%;">
http://img.netpeak.ua/alsey/145994659498_kiss_119kb.jpg

**Comment by jburkhardt** [comment]
First of all, you can simplify your code concerning the date:
```
start_period <- "2016-03-01"
end_period <- Sys.Date()
```
That´s all you need to set the dates.

**Comment by jburkhardt** [comment]
To clearify any misunderstandings: ```transformData``` parses the raw data from xml text to a R data frame including the correct formats of the variables/attributes. If you read the raw data by yourself, you have to change the formats by yourself as well.

Unfonrtunately I can´t reproduce your issue with ```read.csv2``` or ```textConnection```. Moreover this seems to be a problem with you specific machine, settings, system or anything alike.

Due to limited time resources I can´t investigate any further by now as long as there are no new insights.

Please let me know if you find anything new. Maybe Matt has any further ideas.

Kind regards,
Johannes

**Comment by jburkhardt** [comment]
One more thing: Can you try different encoding in textConnection?
```
data <- read.csv2(textConnection(adwordsData), sep = ",", header = F, local = FALSE,
               encoding = c("", "bytes", "UTF-8"))[-1, ]
data <- as.data.frame(data)
```

**Comment by selesnow** [comment]
> One more thing: Can you try different encoding in textConnection?

data <- read.csv2(textConnection(adwordsData), sep = ",", header = F, local = FALSE,
               encoding = c("", "bytes", "UTF-8"))[-1, ]
data <- as.data.frame(data)

did not help

**Comment by selesnow** [comment]
Hello again.

I founed solution, maybe you add this function to package, this function require if system collate is CP1251 windows, and data constain Cirrilyc charactr "я".

```
adwordsEnc <- function(raw, report, apiVersion = "201601") {
  rawutf8 <- iconv(raw, to = "UTF8");
  df <- transformData(rawutf8 , report = report, apiVersion = apiVersion);
  df[] <- lapply(df, function(x) {
    if (is.character(x) || is.factor(x)) {
      iconv(x,from ="UTF8", to ="1251");
      iconv(x,from ="UTF8", to ="1251")
    } else {
      x
    }
  })
  df
}
```

**Comment by jburkhardt** [comment]
thanks! I will look into it again soon.
