### ISSUE TITLE
add TargetingIdeaSelector functionality?

### ISSUE THREAD

**Issue by johnstantongeddes** [jburkhardt/RAdwords#43]
Hi,
Great package! I'm wondering if it's possible to hit the [TargetingIdeaSelector](https://developers.google.com/adwords/api/docs/guides/targeting-idea-service#get_search_volume_data_and_trends) to get search volume data and trends? I might be able to help with this if given some pointers of how to go about it. 

cheers,
John

**Comment by jburkhardt** [comment]
Hi John,
Thanks for the feedback!
RAdwords connects with the [Adwords API Reporting Service](https://developers.google.com/adwords/api/docs/appendix/reports). Search volume, trends and related keywords are available by the [Targeting Idea Service](https://developers.google.com/adwords/api/docs/guides/targeting-idea-service) which is not supported by RAdwords. However there example scripts in other languages (PHP, Python) which you can use as a starting point.
Kind regards,
Johannes

**Comment by johnstantongeddes** [comment]
Thanks Johannes - I've been trying to use the Python client but would prefer to do it in R :)

Still new to Adwords so didn't realize that these services were different 'things'. I'll close this issue and let you re-open if you think it's something that can be added, but seems like it'd need to be it's own package given that it would hit a different service.
