### ISSUE TITLE
Add get_id function to package

### ISSUE THREAD

**Issue by selesnow** [jburkhardt/RAdwords#44]
Hello!
Do you can add function which get list of provide ID accounts in client center accounts?

**Comment by jburkhardt** [comment]
Hi @selesnow,
this is a great idea and we would love to implement this feature! Unfortunately the Adwords API reporting service does not allow to query the account information on client center level.
Best practice is to save the single account IDs in an R object. You then can reference the account IDs from the R object and switch between accounts.
Hope that helps!

**Comment by selesnow** [comment]
Thanks, i have more than 80 projects in MCC, thanks i create vector with IDs, and use him.

**Comment by jburkhardt** [comment]
Best practice is to create a vector containing the account IDs and loop over the vector.

Example:

```R
# authentication, once done you can access all accounts in your MCC
google_auth <- doAuth()
# specify date range, i.e. last two weeks until yesterday
yesterday <- Sys.Date()-1
twoWeeks <- Sys.Date()-14
# create statement
body <- statement(select=c'Date','AccountDescriptiveName','CampaignName','Impressions','Clicks','Cost','Conversions'),
                  report="CAMPAIGN_PERFORMANCE_REPORT",
                  start=twoWeeks,
                  end=yesterday)
#vector of account IDs
accounts <- c("xxx-xxx-xxxx",#Account 1
              "xxx-xxx-xxxx",#Account 2
              "xxx-xxx-xxxx")#Account 3
#loop over accounts and rbind data to dataframe
dataList <- list()
for(account in accounts){
	dataList[account] <- getData(clientCustomerId=account,statement=body,google_auth = google_auth)
}
data <- do.call(rbind, dataList)
```

**Comment by jburkhardt** [comment]
see also https://github.com/jburkhardt/RAdwords/issues/6
