### ISSUE TITLE
Unknown SSL protocol erro

### ISSUE THREAD

**Issue by dcabanillas** [jburkhardt/RAdwords#47]
Hello,
Sometimes I'm getting this error using the RAdwords.

Error in function (type, msg, asError = TRUE)  :
  Unknown SSL protocol error in connection to adwords.google.com:443

My code save the Rsession and afterthat I reuse the google authorization. Do you know which could be the problem?

Best.

**Comment by jburkhardt** [comment]
Please provide:
- OS
- RAdwords version
- R version
- code that produces the error

**Comment by dcabanillas** [comment]
Windows Server 2012 R2 Microsoft Windows Server Versions 6.3 (Build 9600)
RAdwords Versions 0.18
version.string R version 3.2.3 (2015-12-10)

The function

#######################################
#myfunctionA
#parameters:
#account
#begin_data
#end_data
#######################################
myfunctionA <- function(account,begin_data,end_data) {

  #account<-"XXX-XXX-XXXX"

  #end_data<-"2015-12-31"
  #begin_data<-"2015-01-01"


  #Report conversion
  #query_conversion <- statement(select=c('Date','Device',
'ConversionTypeName','Labels','ConversionsManyPerClick','ConversionRateManyPerClick','ConversionValue'),
  #                              report="AD_PERFORMANCE_REPORT",
  #                              start=startday,
  #                              end=yesterday)

  end_data2<-gsub("-", "", end_data)
  begin_data2<-gsub("-", "", begin_data)


  #Metrics information
  #metrics(report = "ACCOUNT_PERFORMANCE_REPORT")

  query_conversion <-
statement(select=c('Date','Device','Clicks','Impressions','Cost','AveragePosition'),
                                report="ACCOUNT_PERFORMANCE_REPORT",
                                start=begin_data2,
                                end=end_data2)




  data_conversion <-
getData(clientCustomerId=account,google_auth=google_auth
,statement=query_conversion)
  print(account)
  print(dim(data_conversion))


  return(data_conversion)
}

On Thu, May 12, 2016 at 10:03 AM, Johannes Burkhardt <
notifications@github.com> wrote:

> Please provide:
>
>    - OS
>    - RAdwords version
>    - R version
>    - code that produces the error
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jburkhardt/RAdwords/issues/47#issuecomment-218687436>
>



-- 
bye
--david

**Comment by jburkhardt** [comment]
1. Please update RAdwords to version 0.1.9 from github.
  ```
  require(devtools)
  install_github('jburkhardt/RAdwords')
  ```
2. You don´t need ```end_data2<-gsub("-", "", end_data)```. Format ```"2015-12-31"``` works with RAdwords.
3. I cannot reproduce the SSL error since I do not develop on Windows Server 2012.
4. When does the SSL error occur: With ```authentication``` or with ```getData```?
5. Does the SSL error just occur occasionaly or always?

**Comment by dcabanillas** [comment]
Good afternoon Jonahnnes,

I have changed to 0.1.9 but the error persists. Th error occurs occasionaly.

The traceback error is:

Error in function (type, msg, asError = TRUE)  :
  Unknown SSL protocol error in connection to accounts.google.com:443
10
fun(structure(list(message = msg, call = sys.call()), class = c(typeName,
    "GenericCurlError", "error", "condition")))
9
function (type, msg, asError = TRUE)
{
    if (!is.character(type)) {
        i = match(type, CURLcodeValues) ...
8
.postForm(curl, .opts, .params, style)
7
RCurl::postForm("https://accounts.google.com/o/oauth2/token",
    refresh_token = google_auth$access$refresh_token, client_id =
google_auth$credentials$c.id,
    client_secret = google_auth$credentials$c.secret, grant_type =
"refresh_token",
    style = "POST", .opts = list(ssl.verifypeer = FALSE))
6
rjson::fromJSON(RCurl::postForm("https://accounts.google.com/o/oauth2/token",

    refresh_token = google_auth$access$refresh_token, client_id =
google_auth$credentials$c.id,
    client_secret = google_auth$credentials$c.secret, grant_type =
"refresh_token",
    style = "POST", .opts = list(ssl.verifypeer = FALSE)))
5
refreshToken(google_auth)
4
getData(clientCustomerId = account, google_auth = google_auth,
    statement = query_conversion)
3
myfunctionA(account, first_day, last_day)
2
rbind(dataList[[account]], myfunctionA(account, first_day, last_day))
1
myfunctionAdwords(l_update)

On Thu, May 12, 2016 at 11:50 AM, Johannes Burkhardt <
notifications@github.com> wrote:

>
>    1. Please update RAdwords to version 0.1.9 from github. require(devtools)
>    install_github('jburkhardt/RAdwords')
>    2. You don´t need end_data2<-gsub("-", "", end_data). Format
>    "2015-12-31" works with RAdwords.
>    3. I cannot reproduce the SSL error since I do not develop on Windows
>    Server 2012.
>    4. When does the SSL error occur: With authentication or with getData?
>    5. Does the SSL error just occur occasionaly or always?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jburkhardt/RAdwords/issues/47#issuecomment-218711018>
>



-- 
bye
--david

**Comment by mbannert** [comment]
Do you have a persistent API for your server? Or is it just some local windows server with an IP that might change? I had problems with Google Auth processes a while cause Google thought someone else had added a new device and kept blocking me. After working through Google's developers console I was able to convince them it was me. Given that your problem only occurs occasionally I don't think it has something to do with our package. From what I can see it's rather and auth or connectivity issue. 

Also it might be an RCurl or curl problem. curl has had a change or two dealing with SSL.

**Comment by dcabanillas** [comment]
Do you have any suggestion to solve my problem?

To contact with any google-forum???

Best.

On Thu, May 12, 2016 at 4:35 PM, Matt Bannert <notifications@github.com>
wrote:

> Do you have a persistent API for your server? Or is it just some local
> windows server with an IP that might change? I had problems with Google
> Auth processes a while cause Google thought someone else had added a new
> device and kept blocking me. After working through Google's developers
> console I was able to convince them it was me. Given that your problem only
> occurs occasionally I don't think it has something to do with our package.
> From what I can see it's rather and auth or connectivity issue.
>
> Also it might be an RCurl or curl problem. curl has had a change or two
> dealing with SSL.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jburkhardt/RAdwords/issues/47#issuecomment-218776817>
>



-- 
bye
--david

**Comment by jburkhardt** [comment]
It looks like a curl/RCurl issue on your system.
Can you run the following code before you run your own function:
```
refreshToken = function(google_auth) {
  # This function refreshes the access token. The access token deprecates after one hour and has to updated with the refresh token.
  #
  # Args:
  #   access.token$refreh_token and credentials as input
  # Returns:
  #   New access.token with corresponding time stamp
  
    rt = rjson::fromJSON(RCurl::postForm('https://accounts.google.com/o/oauth2/token', 
                           refresh_token=google_auth$access$refresh_token, 
                           client_id=google_auth$credentials$c.id,
                           client_secret=google_auth$credentials$c.secret, 
                           grant_type="refresh_token", 
                           style="POST",
                           .opts = list(ssl.verifypeer = TRUE))) #Fix SSL Certificate problem on Windows
    access <- rt
    
    access
}
```
Does the error still occur?

**Comment by dcabanillas** [comment]
Hello Johannes,

The respond of your function in my case is
$access_token
[1] "MY TOKEN"
$token_type
[1] "Bearer"
$expires_in
[1] 3600

But I'm getting the same error


Error in function (type, msg, asError = TRUE)  :
  Unknown SSL protocol error in connection to adwords.google.com:443
8
fun(structure(list(message = msg, call = sys.call()), class = c(typeName,
    "GenericCurlError", "error", "condition")))
7
function (type, msg, asError = TRUE)
{
    if (!is.character(type)) {
        i = match(type, CURLcodeValues) ...
6
curlPerform(curl = curl, .opts = opts, .encoding = .encoding)
5
RCurl::getURL(paste("https://adwords.google.com/api/adwords/reportdownload/v",

    apiVersion, sep = ""), httpheader = c(Authorization = google.auth,
    developerToken = credlist$auth.developerToken, clientCustomerId =
clientCustomerId,
    includeZeroImpressions = includeZeroImpressions), postfields =
statement,  ...
4
getData(clientCustomerId = account, google_auth = google_auth,
    statement = query_conversion)
3
myfunctionA(account, first_day, last_day)
2
rbind(dataList[[account]], myfunctionA(account, first_day, last_day))
1
myfunctionAdwords(l_update)

On Thu, May 12, 2016 at 5:13 PM, Johannes Burkhardt <
notifications@github.com> wrote:

> It looks like a curl/RCurl issue on your system.
> Can you run the following code before you run your own function:
>
> refreshToken = function(google_auth) {
>   # This function refreshes the access token. The access token deprecates after one hour and has to updated with the refresh token.
>   #
>   # Args:
>   #   access.token$refreh_token and credentials as input
>   # Returns:
>   #   New access.token with corresponding time stamp
>
>     rt = rjson::fromJSON(RCurl::postForm('https://accounts.google.com/o/oauth2/token',
>                            refresh_token=google_auth$access$refresh_token,
>                            client_id=google_auth$credentials$c.id,
>                            client_secret=google_auth$credentials$c.secret,
>                            grant_type="refresh_token",
>                            style="POST",
>                            .opts = list(ssl.verifypeer = TRUE))) #Fix SSL Certificate problem on Windows
>     access <- rt
>
>     access
> }
>
> Does the error still occur?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jburkhardt/RAdwords/issues/47#issuecomment-218788828>
>



-- 
bye
--david

**Comment by mbannert** [comment]
@dcabanillas I am really just guessing here, but I'd look into Rcurl / curl issues with SSL. 
Threads like this: http://stackoverflow.com/questions/6736895/using-rcurl-with-https
or
http://stackoverflow.com/questions/17411313/ssl-verification-causes-rcurl-and-httr-to-break-on-a-website-that-should-be-le

**Comment by jburkhardt** [comment]
What happens if you run following RCurl settings first and then execute your code?
```options(RCurlOptions = list(cainfo = system.file("CurlSSL", "cacert.pem", package = "RCurl")))```

**Comment by 123saga** [comment]
i have same issue: 
R version: 3.1 
OS: Ubuntu 14.04.3
Rcurl Version: 1.95-4.8
RAdwords Version: 0.1.9
