### ISSUE TITLE
AD_PERFORMANCE_REPORT

### ISSUE THREAD

**Issue by dcabanillas** [jburkhardt/RAdwords#49]
I'm calling the following code:

query_traffic <- statement(select=c('Date','Device','AdType','AccountDescriptiveName','CampaignName','AdGroupName','AdGroupStatus','Status'),
                               report="AD_PERFORMANCE_REPORT",
                               start=today, 
                               end=today)
    
    
    try_backoff(data_traffic <- getData(clientCustomerId=account, google_auth=google_auth ,statement=query_traffic),verbose = TRUE, max_attempts = 5)
    

It works properly but when all the metrics in an ad are equals to zero this will not is included in the data. It is excluded. Right?

**Comment by jburkhardt** [comment]
In ```getData()```you can use the argument ```includeZeroImpressions = TRUE``` if you want to get ads that have not generated any data. Default is ```FALSE```.

**Comment by prasoonsrivas** [comment]
In 
body <- statement(select=c('Date','Cost','Impressions','AveragePosition','CampaignName','Clicks','Ctr',
                           'Conversions','Convertedclicks','Labels'),

I am not getting the Convertedclicks column.

**Comment by jburkhardt** [comment]
Please be precise with your questions!
I assume you use the ```AD_PERFORMANCE_REPORT```.
You have a syntax error in Convertedclicks. The attribute/variable name is: ```ConvertedClicks```

With ```metrics("AD_PERFORMANCE_REPORT")``` you can print all available metrics.
Please review your code in advance next time!
