### ISSUE TITLE
Error with LABEL_REPORT -> DURING_CLAUSE_REQUIRES_DATE_COLUMN

### ISSUE THREAD

**Issue by diegocgaona** [jburkhardt/RAdwords#51]
Hi,

I'm trying to retrieve a list of IDs of the labels of my account (I need to use then as filter, the API does not accept filtering by the LabelName) but I'm having some errors.

The query:
```
test <- statement(select=c('LabelName','LabelId'),
                    report="LABEL_REPORT",
                    start="20160711",
                    end="20160727")
test2 <- getData(clientCustomerId='XXX-XXX-XXX', google_auth=adw_auth, statement=test)

test2
```
The error I receive:

`"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><reportDownloadError><ApiError><type>QueryError.DURING_CLAUSE_REQUIRES_DATE_COLUMN</type><trigger></trigger><fieldPath></fieldPath></ApiError></reportDownloadError>"`

I'm using the RAdwords 0.1.10

It's something I'm doing wrong?

Thanks, Diego

**Comment by jburkhardt** [comment]
Thanks! Your code looks fine. In fact there is an error with the statement handling for the ```LABEL_REPORT```.
The ```LABEL_REPORT```does not support dates. This means one can not provide dates within the query/statement to filter within label reports.
I fixed the issue just now. Please reinstall RAdwords from the github repo and test your code once again:
```
require(devtools)
install_github('jburkhardt/RAdwords')
```
I hope that this works now!

**Comment by diegocgaona** [comment]
Many thanks @jburkhardt ! Is working fine now.
