### ISSUE TITLE
How to use doAuth in a script that in scheduled as a cron job

### ISSUE THREAD

**Issue by simran-k** [jburkhardt/RAdwords#52]
My script runs fine in Rstudio, however, I keep getting, 

`Authentication process needs your Client ID from the Adwords API project for native apps
Paste the Client ID here`

when I run my script as a cron job.

I see that the documentation says that this function requires user interaction but I believe I've been able to run it through cron before. It somehow started throwing this very recently. 

Also, When I run this script in rstudio, it never really asks me to provide a client ID as such. Where has it been getting the client ID from?

I've been using it like:

google_auth <- doAuth(save = T);

and 
I've a file in my working directory, `.google.auth.RData`. I've also seen that if I first load this file, 

load("/home/rstudio/.google.auth.RData")

and comment out doAuth, I don't get this error through cron either but I believe it can't work since the access token is going to expire in an hour or so. 

How do I do it? How I've been able to use doAuth for a cron up until now and why does it never ask for client ID when I run it thorough Rstudio?

I've made all my files executable in my working directory so sure the cron job should be able to access any files that are there.

How to make this work?

**Comment by mbannert** [comment]
Did you change your Google password? You do need some authentication and thus pass your client ID there.  Maybe it got saved in the past and that's why it worked. Can you make it work by passing it once? That being said there is a routine to work with refresh token.

**Comment by jburkhardt** [comment]
You only need to run ```doAuth``` once. Do not rerun ```doAuth``` in the batch script. Make sure to set correct working directory in the batch script! Did you try to save the google_auth object manually and load it in the batch script?
Initial Auth in RStudio session:
```
google_auth <- doAuth()
save(google_auth, "/your/directory")
```
Batch script:
```
setwd(/directory/of/rproject)
load(google_auth)
```
fyi: the ```loadData```function refreshes the token automatically if it is expired after one hour. This is no a problem with batch scripts.
hope that helps
