### ISSUE TITLE
Label report should have no DURING clause

### ISSUE THREAD

**Issue by Positivapatrik** [jburkhardt/RAdwords#53]
Fetching the label report gives an error as statement() adds default DURING clause which should not be included for the label report. Works fine if the statement is modified manually to remove the DURING clause.

#Will not work
labelReportQuery <- statement(select=c('LabelName'), report = "LABEL_REPORT")
#Works if labelQuery is modified
labelReportQuery[1] <- "__rdquery=SELECT+LabelName+FROM+LABEL_REPORT&__fmt=CSV"

**Comment by jburkhardt** [comment]
Thanks! I think this issue should be fixed already. Pleas update the package from the github repository again. See here: https://github.com/jburkhardt/RAdwords/issues/51

**Comment by Positivapatrik** [comment]
Oh, Apparently forgot to pull the latest version. Great and thanks! :)
