### ISSUE TITLE
Error in subset with API version change

### ISSUE THREAD

**Issue by simran-k** [jburkhardt/RAdwords#56]
I started getting this error this morning:

```
Error in subset(reportType, Type == "Double") : 
  object 'reportType' not found
```

with change in apiVersion. It looks like it by default uses 201603 which now has been deprecated.
If I do not pass apiVersion in getData call, it gives:

`"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><reportDownloadError><ApiError><type>RequestError.UNSUPPORTED_VERSION</type><trigger>You are accessing an AdWords API version v201603 that has been discontinued. Calls to this version may fail. Please visit the AdWords API blog for information on migration to the new AdWords API version.</trigger><fieldPath></fieldPath></ApiError></reportDownloadError>"` in response to every API call.

If I instead change it to 201605 it gives error is subset error.I tried it for Campaign performance reports and some others as well but I keep getting it irrespective of the report I am trying to download.

Similarly, if I pass apiVersion to reports function:

```
xyz <- RAdwords::reports(apiVersion = "201605")
print(xyz)
```

it gives:

`Error in sub(".csv", "", reportTypes) : object 'reportTypes' not found
`
On other hand If I pass 

```
xyz <- RAdwords::reports(apiVersion = "201603")
print(xyz)
```

it works
Looks like the problem here is with the version that gets passed?

**Comment by simran-k** [comment]
Anyone?please? Is there going to be an update about this?

**Comment by 123saga** [comment]
I am facing the similar error, no data being returned with default version and if pass a specific version, it is failing with  `object 'reportType' not found` error

**Comment by simran-k** [comment]
@jburkhardt : Hoping to hear back from you on this

**Comment by jburkhardt** [comment]
@simran-k @123saga 
Thanks for your feedback! I will look into the issue soon and migrate the RAdwords package towards the latest Adwords API version 201609. I should be done with this by the end of the week. In the meanwhile please make sure you run with RAdwords 0.1.10 which should work fine with the API v201605.

**Comment by simran-k** [comment]
Hey, Thanks. I look forward to the update. Could you please specify how to
upgrade existing RAdwords package to the specified version?

**Comment by jburkhardt** [comment]
Just run the following code:

```
require(devtools)
install_github('jburkhardt/RAdwords')
```

**Comment by jburkhardt** [comment]
@123saga @simran-k 
I migrated RAdwords (version 0.1.11) towards the latest Adwords API version v201609 on my github repository. Please update the package and let me know if you are fine!
