### ISSUE TITLE
google_auth issues

### ISSUE THREAD

**Issue by migfern** [jburkhardt/RAdwords#57]
Hi Johannes,

Relatively new to R language in general and have just come across a road block at this line
data <- getData(clientCustomerId='xxx-xxx-xxxx', google_auth=google_auth ,statement=body)
"google_auth=google_auth" <---Should i be placing an access token here?
What data should i be placing within this line of code?

Sorry for the noobish question, appreciate it!

**Comment by migfern** [comment]
Trying 74.125.23.139...
* Connected to adwords.google.com (74.125.23.139) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: adwords.google.com
* Server certificate: Google Internet Authority G2
* Server certificate: GeoTrust Global CA
* Server certificate: Equifax Secure Certificate Authority
> POST /api/adwords/reportdownload/v201509 HTTP/1.1
Host: adwords.google.com
Accept: */*
Authorization: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
developerToken: xxxxxxxxxxxxxxxxxxxxxxxxxx
clientCustomerId: xxx-xxx-xxxx (
includeZeroImpressions: FALSE
Content-Length: 88
Content-Type: application/x-www-form-urlencoded

* upload completely sent off: 88 out of 88 bytes
< HTTP/1.1 400 Bad Request
< Content-Type: text/html; charset=UTF-8
< Date: Sun, 13 Nov 2016 10:45:16 GMT
< Expires: Sun, 13 Nov 2016 10:45:16 GMT
< Cache-Control: private, max-age=0
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< Server: GSE
< Alt-Svc: clear
< Accept-Ranges: none
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< 
* Connection #0 to host adwords.google.com left intact

Thats what i'm left with in my console, not sure where i've gone wrong here.
Any support would be great, thanks guys!!

**Comment by jburkhardt** [comment]
Hi @migfern 

```google_auth```is a R object which you create with the ```doAuth()``` function. This object contains all your credential information and you use this object in the ```getData()``` function.
```
library(RAdwords)
google_auth <- doAuth()
```
I am working on a detailed documentation with a stey by step instruction:
https://github.com/rstats-lab/radwords-docs/blob/master/docs/auth.md

I hope this will help you!
Let me know if you succeed.
Kind regards,
Johannes

**Comment by migfern** [comment]
Thanks for the reply Jo, appreciated!!

Makes sense that we are storing our information in the doAuth() function.
For some reason my request is returning a 400 status code?
I've tried diagnosing the issue for the last couple of days but can't seem to find a resolution.

Is there anything you can see in my 'second' post above that rings alarm bells?
I've input all my authentication details correctly, can't seem to find the issue.

 Your time's appreciated! Thank you!

**Comment by jburkhardt** [comment]
Unfortunately the prompt output from your previous post does not help much.
Do you fulill the following requirements?
https://github.com/rstats-lab/radwords-docs/blob/master/docs/requirements.md
How does the ```google_auth``` object look like after running ```google_auth <- doAuth()```?

**Comment by migfern** [comment]
Hey Jo,

I'm still have some issues accessing Adwords through the API.
Below are the variables my google_Auth object contains.
If you need more info, let me know!

My Google Auth object contains four variables.
1. Client ID
2. Client secret 
3. auth.developerToken
4. c.token

access
1. access_token
2. expires_in
3. refresh_token
4. token_type
5. timeStamp

**Comment by jburkhardt** [comment]
@migfern 
With the information you provide it is really difficult to help you since I cannot see at which step in the auth, query, load data - process your script fails.
At least it looks like the authentication with the Adwords API is successfull.

I published a new documentation. Please read and follow the instruction carefully and you should be fine:
http://jburkhardt.github.io/RAdwords/
You will find all the information to get started!

I suppose your are not far from your goal and there is a minor mistake in your script or anything alike. I suspect you use the AdWords MCC Id instead ot the Adwords Account ID within ```getData```.

As there is no bug with the code of the package I will close this issue by now. Please let me know if you succeed!
