### ISSUE TITLE
Is it possible set on necessary data(clientid,client secret) as parameters, not via command line?

### ISSUE THREAD

**Issue by googlogmob** [jburkhardt/RAdwords#59]
And another question: 
Is it possible make getting data from AdWords completely auto, without manual operation?

**Comment by jburkhardt** [comment]
Concerning your **first question**:

After running the authentication process with
```
google_auth <- doAuth()
```
you can save the ```google_auth```object and use it in later instances. This way you only have to set the credentials one time.

**Second question**:

Of course you can run the R code scripts in batch mode and use a taskmanager like crontab to execute the scripts regularly.

I recommend to read the package documentation here:
http://jburkhardt.github.io/RAdwords/
