### ISSUE TITLE
QuotaCheckError.INVALID_TOKEN_HEADER with RAdwords' getData()

### ISSUE THREAD

**Issue by laresbernardo** [jburkhardt/RAdwords#61]
I am getting the following code when running the getData():

```
body <- statement(select=c('CampaignName','Clicks','AveragePosition','Cost','Ctr'),
                  where="CampaignName = 'Seguros de Carro 2016'",
                  report="CAMPAIGN_PERFORMANCE_REPORT",
                  start="20170201",
                  end="20170202")
getData(clientCustomerId='235-689-2018', google_auth=google_auth, statement=body, includeZeroImpressions=T)
```

`[1] "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><reportDownloadError><ApiError><type>QuotaCheckError.INVALID_TOKEN_HEADER</type><trigger>2356892018</trigger><fieldPath></fieldPath></ApiError></reportDownloadError>"`

This article doesn't really help: https://developers.google.com/adwords/api/docs/common-errors#QuotaCheckError.INVALID_TOKEN_HEADER

Hope you can help me with that!! Thanks @refik @mbannert @jburkhardt @djuery 👍

**Comment by jburkhardt** [comment]
Smells like invalid credentials or adwords test account or missing Adwords API Developer Token.
Please make sure you set up your Adwords MCC correctly. We have detailed instructions here:
http://jburkhardt.github.io/RAdwords/requirements/
