### ISSUE TITLE
Strings in getData is truncated

### ISSUE THREAD

**Issue by googlogmob** [jburkhardt/RAdwords#62]
Hello
Operating System: Windows Server 2012R2, Windows 7
R Version: 3.3.2
RAdwords version: 0.1.11
R Code:
`library(RAdwords)
google_auth <- readRDS("C:/AdWordsAuth.RData")
body <- statement(select = c("CampaignId", "CampaignName", "CampaignStatus", "StartDate", "EndDate", "Amount"),
    report = "CAMPAIGN_PERFORMANCE_REPORT")
cert <- system.file("CurlSSL", "ca-bundle.crt", package = "RCurl")
data <- getData(clientCustomerId = "", google_auth = google_auth, statement = body)
data`

In Visual Studio all works fine:
http://prntscr.com/ehajl7

In result is 51 rows

But using RStudio or RGui I noticed than strings in getData is truncated:
http://prntscr.com/ehajrw

The same problem is with getting adgroups, ads.

Please tell the reason for this error

PS.Thanks for this useful tool

**Comment by jburkhardt** [comment]
Hello,
I never experienced the same behaviour.
Here a few things you could make sure:
- Do you use the same RAdwords version on each system?
- Please set ```start``` and ```end``` in ```statement()```explicitely. Otherwise it defaults to values set in the package which might be different in differing package versions. I never had a use case where I leave out ```start``` and `` end```.
- Antoher reason might be encoding issues with cyrillic letters. Could you please specify the system encodings on your different operating systems?
- Please run ```getData()```with ```transformation=FALSE, changeNames=FALSE```. The output is XML now. Is there still a difference in the output?

Hope this helps for further investigation!

**Comment by googlogmob** [comment]
Hello

**Comment by jburkhardt** [comment]
It seems there are encoding problems with cyrillic letters correlated with the locale of your operating system.
Use ```Sys.getlocale()``` to gather information about the locale of your different opertaing systems. I guess the locale settings on the Microsoft Visual Studio differ from the locale settings on your local machine.
We have a related issue here: https://github.com/jburkhardt/RAdwords/issues/60
