### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by XoliloX** [jburkhardt/RAdwords#63]
Hi all,

I wanted to try out this packages but got the following issue :

Warning in install.packages :
  package ‘RAdwords’ is not available (for R version 3.3.2)

Being new to R makes it difficult for me to figure out what to do...

Thanks a lot in advance for your help !!

D.

**Comment by jburkhardt** [comment]
Hi,
there shouldn´t be any problems with the package installation.
Please follow the guide in our documentation:
http://jburkhardt.github.io/RAdwords/

**Comment by mbannert** [comment]
@XoliloX : it's recommended to install the github version, as described in the documentation @jburkhardt has posted. Yet that requires devtools to be installed. Are sure you installed devtools properly, cause this is an issue sometimes with unexperienced users, particularly when they're on Windows.

**Comment by XoliloX** [comment]
Hi Guys,

Thanks a lot for your feedback. Issue was solved with dependencies = TRUE.

Thanks a lot !!!!!
