### ISSUE TITLE
Pulling "Active" Campaigns

### ISSUE THREAD

**Issue by ericbrownaustin** [jburkhardt/RAdwords#64]
Is there a way to pull only "active" campaigns?  I have gone through the campaign reports included in the package but have not found a way to do so.

![image](https://cloud.githubusercontent.com/assets/11723172/24305381/be3801d4-108a-11e7-976a-abd3ed326f1b.png)

**Comment by jburkhardt** [comment]
Best practice is to query the ```CampaignStatus```column. Then you can subset ```enabled``` campaigns.
```
body <- statement(select=c('CampaignName','CampaignStatus'),
                  report="CAMPAIGN_PERFORMANCE_REPORT",
                  start="2017-01-01", end="2017-01-02")
data <- getData(clientCustomerId="***-***-****",
                google_auth=google_auth,
                statement=body)
data <- subset(data, Campaignstate == "enabled")
```
