### ISSUE TITLE
doAuth() does not let me put in credentials

### ISSUE THREAD

**Issue by braggbear** [jburkhardt/RAdwords#65]
It was working a week ago but now when i do google_auth <- doAuth() it doesn't allow me to put in my creditials and nothing is returned (it just goes to the next line).  I have tried system("rm .google.auth.RData") but that only gives me a status 127 warning.  

I am using R Version 3.4.0.   Thanks for your help.

**Comment by mbannert** [comment]
@jburkhardt haven't updated to 3.4 yet, seems like some package (like seasonal) have/had issues with 3.4. Do we know anything about 3.4 behavior yet. @braggbear: did you update R in between now and 'a week ago' ?

**Comment by jburkhardt** [comment]
@braggbear 
Could you give us a bit more information about:
- Operating System
- RAdwords version
- Do you use RStudio?

Status 127 - I guess ```system("rm .google.auth.RData") ```did not work. Please use the terminal and navigate to your working directory and delete the file ```.google.auth.RData```manually. The try again.

If this still does not work, then start a completely new Rproject (RStudio) or R session with a separate working directory.

**Comment by braggbear** [comment]
Thank you for your quick responses.  I was able to fix the issue by going into the working directory and erasing the file and then rerunning it.  Thanks!
