### ISSUE TITLE
RAdwords / RGoogleAnalytics clash?

### ISSUE THREAD

**Issue by scottpete** [jburkhardt/RAdwords#66]
I'm getting the error message below when trying to retrieve Adwords data using RAdwords::getData(...) under certain circumstances.

I discovered that upon reloading RStudio, all works fine again. It appears that the error returns immediately after running RGoogleAdwords::GetReportData(..)

Example:

> **awData <- RAdwords::getData(clientCustomerId=AdwordsID, google_auth=google_auth, statement=body,   transformation = TRUE, changeNames = TRUE, apiVersion="201702")**
( above was successful )

> **gaData <- RGoogleAnalytics::GetReportData(ga.query, token, paginate_query=FALSE)**
( above also successful )

> **awData <- RAdwords::getData(clientCustomerId=AdwordsID, google_auth=google_auth, statement=body,   transformation = TRUE, changeNames = TRUE, apiVersion="201702")**

_Warning messages:
1: In curlSetOpt(..., .opts = .opts, curl = h, .encoding = .encoding) :
  Error setting the option for # 2 (status = 4) (enum = 10097) (value = 0x1019815a0): A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision. <not set>
2: In curlSetOpt(..., .opts = .opts, curl = h, .encoding = .encoding) :
  Error setting the option for # 2 (status = 4) (enum = 10097) (value = 0x10a62cbc0): A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision. <not set>_

The only way I have been able to resume RAdwords is to close and reload RStudio, and AVOID using RGoogleAnalytics prior to RAdwords.

Any suggestions would be appreciated.
Thanks,
Scott

RAdwords v0.1.12
RGoogleAnalytics v0.1.5
RStudio Version 1.0.143
R version 3.3.3 (2017-03-06)
curl v2.6
RCurl v1.95-4.8

**Comment by jburkhardt** [comment]
Hi @scottpete,
in the issue above you state:
```
gaData <- RGoogleAdwords:: GetReportData(ga.query, token, paginate_query=FALSE),silent=FALSE)
```
I have two concerns about this:
- I guess you mean ```RGoogleAnalytics::GetReportData(...)``` instead of ```RGoogleAdwords:: GetReportData``` ?
- Moreover there might be a syntax error with two closing brackets: ```paginate_query=FALSE),silent=FALSE)```

Could you please check this?

**Comment by scottpete** [comment]
Hi @jburkhardt, thank you for your reply.

Yes, you are correct with both of your notes. I had made an error while trying to format my post here, and have since corrected it in the original post above.

Please also note that the 2nd RAdwords call does return the correct data, but produces the error message shown above, only after the RGoogleAnalytics::GetReportData(...) call is made.

Here is the code to reproduce the error, if it helps:

`rm(awData, gaData)`

> ## Simple call to pull some Adwords data:

```
library(RAdwords)
google_auth <- doAuth(save = T)
body <- statement(select=c('CampaignName','Impressions','Clicks'),
                  report="CAMPAIGN_PERFORMANCE_REPORT", start="2016-12-01",end="2016-12-31")

awData <- RAdwords::getData(clientCustomerId=AdwordsID, google_auth=google_auth, statement=body,  transformation = TRUE, changeNames = TRUE, apiVersion="201702")
View(awData) 
```

> ## Simple call to pull some Google Analytics data:

```
require(RGoogleAnalytics)
token <- Auth(client.id,client.secret); # same values used for RAdwords
ValidateToken(token)
query.list<- Init(start.date="2016-12-01",end.date="2016-12-31",
                  dimensions = "ga:adwordsCampaignID",
                  metrics = "ga:users", sort = NULL,max.results=1000,table.id=id)

ga.query <- QueryBuilder(query.list)
gaData <- RGoogleAnalytics::GetReportData(ga.query, token, paginate_query=FALSE)
View(gaData)
```

> ## Simple call to pull additional Adwords data returns an error message (**but works**)

```
body <- statement(select=c('CampaignName','Impressions','Clicks'),
                  report="CAMPAIGN_PERFORMANCE_REPORT", start="2016-11-01",end="2016-11-30")
awData <- RAdwords::getData(clientCustomerId=AdwordsID, google_auth=google_auth, statement=body,
          transformation = TRUE, changeNames = TRUE, apiVersion="201702")
View(awData)

```

**Comment by jburkhardt** [comment]
Thanks for the detailed describtion.

The warning message relates to curl setting of your operating system (OS). What OS are you running on?

I did not figure out how RGoogleAnalytics interacts with curl and if this results in changes to the curl settings of your system.

Fortunately you can pull data from the Adwords API with the second RAdwords call.

Do you use two different Google API projects, one for Google Analytics and one for Google Adwords? This should prevent authentication interferences between the two packages.

Just a hint:
I stopped using the RGoogleAnalytics package quiet a while ago and switched to RGA. RGA is perfect if you want to pull huge amounts of data without sampling and moreover RGA incorporates an interface to the Google Analytics Multi Channel Funnel API. I really recommend using RGA.

**Comment by scottpete** [comment]
I'm running MacOS Sierra 10.12.4

Thanks for the tip on RGA - I'll check it out.
