### ISSUE TITLE
Report Download Error - INVALID_REPORT_DEFINITION_FORMAT

### ISSUE THREAD

**Issue by Timmwardion** [jburkhardt/RAdwords#67]
Hi There,

I'm just figuring out how to use this package and I've struck a problem. Authentication appears to work but the RCURL call in the getData function returns an error meaning I get an empty data set returned by the getData function.

The error is "ReportDownloadError.INVALID_REPORT_DEFINITION_FORMAT"
The error detail is "Invalid Report format: CSV FROM ACCOUNT_PERFORMANCE_REPORT DURING 20170101,20170110"

The output of the statement function is:
```
[1] "__rdquery=SELECT+__rdquery=SELECT+Clicks,AveragePosition,Cost,Ctr+FROM+ACCOUNT_PERFORMANCE_REPORT+DURING+20170101,20170110&__fmt=CSV+FROM+ACCOUNT_PERFORMANCE_REPORT+DURING+20170101,20170110&__fmt=CSV"
attr(,"reportType")
[1] "ACCOUNT_PERFORMANCE_REPORT"
```
The Code that generates it is copy and pasted from your examples but for clarity here it is.

```
library(RAdwords)
#start authentication process
google_auth <- doAuth(save = T)

body <- statement(select=c('Clicks','AveragePosition','Cost','Ctr'),
report="ACCOUNT_PERFORMANCE_REPORT",
start="2017-01-01",
end="2017-01-10")
body<-statement(body)
data <- getData(clientCustomerId='xxx-xxx-xxxx', google_auth=google_auth ,statement=body)
```

My guess is that the statement function is malformed somehow but as this is my first time working with the adwords api, I'm a bit stumped as to what that might be. Double-declaration of the output format seems to be suspiciuous.

**Comment by jburkhardt** [comment]
Hi,
the code is not correct. The line ```body<-statement(body)``` is needless. You use the function ```statement()``` twice.
Please try:
```R
library(RAdwords)
#start authentication process
google_auth <- doAuth(save = T)

body <- statement(select=c('Clicks','AveragePosition','Cost','Ctr'),
                                report="ACCOUNT_PERFORMANCE_REPORT",
                                start="2017-01-01",
                                end="2017-01-10")

data <- getData(clientCustomerId='xxx-xxx-xxxx', google_auth=google_auth ,statement=body)
```
Where did you find this example? I would like to correct this in order to prevent further confusion.

**Comment by Timmwardion** [comment]
Oh! I can't believe I didn't pick that one up. Thanks.

I thought I got it from your RAdwords landing page but now I look again, I seem to have made a mistake copying my own code around.
