### ISSUE TITLE
Get all Client IDs of Manager Account

### ISSUE THREAD

**Issue by S-UP** [jburkhardt/RAdwords#68]
Hi!

Thanks for this lovely package!

We are managing lots of accounts under one Manager ID. Is there a function that allows to grab all Client IDs managed by a particular Manager Account?

Or do I have to collect this manually by clicking on each and every account and copying the Client ID?

Many thanks!

**Comment by jburkhardt** [comment]
Hi @S-UP 

No it´s not possible to download all client IDs. Unfortunately there are limitations with the Adwords API.

Here is a workaround solution:
http://jburkhardt.github.io/RAdwords/faq/#list-account-ids

Hope that helps!
Johannes

**Comment by ben519** [comment]
Note that this is now possible with [ManagedCustomerService](https://developers.google.com/adwords/api/docs/reference/v201809/ManagedCustomerService).
