### ISSUE TITLE
ERROR DOWNLOADING DATA 

### ISSUE THREAD

**Issue by eviling** [jburkhardt/RAdwords#71]
Hello,

I have been trying to connect to google adwords, but I get this error:

>  SSL certificate problem: unable to get local issuer certificate

I alredy installed again RAdwords using install_github('jburkhardt/RAdwords')

Please help,

Thanks

**Comment by mbannert** [comment]
What OS, R version are you using? Is this your first time using RAdwords or did you use our package before?

**Comment by eviling** [comment]
Hi,

Until two weeks ago it works perfect my connection to GA using this package. 

My R version is 3.4.1. and I am using Windows 10.

I think is related with [https://github.com/jeroen/curl/issues/122](url), but I did the steps and I still get the same error SSL

**Comment by eviling** [comment]
The problem is on the function getData with the RCurl section.

The code needs to be modify to FALSE in the ssl.verifypeer, but I dont understand why.

Here is the modified function:

`getData <- function(clientCustomerId,
                    google_auth,
                    statement,
                    apiVersion = "201708",
                    transformation=TRUE,
                    changeNames=TRUE,
                    includeZeroImpressions=FALSE,
                    verbose=FALSE){
  
  # for a better overview split google auth
  access <- google_auth$access
  credlist <- google_auth$credentials
  
  # because access token can expire 
  # we need to check whether this is the case
  if(as.numeric(Sys.time())-3600 >= access$timeStamp){
    access <- refreshToken(google_auth) 
  } 
  # getData posts the Adwords Query Language Statement and retrieves the data.
  #
  # Args:
  #   clientCustomerId: Adwords Account Id
  #   statement: Object generated with statement() including the Api request.
  #   transformation: If true, transformData() will be applied on data. Else raw csv data will be returned.
  # 
  # Returns:
  #   Dataframe with the Adwords Data.
  google.auth <- paste(access$token_type, access$access_token)
  cert <- system.file("CurlSSL", "ca-bundle.crt", package = "RCurl")#SSL certification Fix for Windows
  data <- RCurl::getURL(paste("https://adwords.google.com/api/adwords/reportdownload/v",apiVersion,sep=""),
                        httpheader = c("Authorization" = google.auth,
                                       "developerToken" = credlist$auth.developerToken,
                                       "clientCustomerId" = clientCustomerId,
                                       "includeZeroImpressions" = includeZeroImpressions),
                        postfields=statement,
                        verbose = verbose,
                        cainfo = cert, #add SSL certificate
                        ssl.verifypeer = FALSE)
  
  # check 
  valid <- grepl(attr(statement,"reportType"),data)
  
  if (transformation & valid){
    data <- transformData(data,
                          report = attributes(statement)$reportType,
                          apiVersion = apiVersion)
    if (changeNames){
      data <- changeNames(data)
    }
  }
  data  
}`

I believe is related with windows configuration, maybe the funcion getData needs to be update

**Comment by AlexandreCV** [comment]
Hi,

First of all, thank you @jburkhardt for this package, I use it on a regular basis and it saves me a lot of time!
I am encountering the same issue as described above by @eviling  since yesterday evening. Until then, my queries were working perfectly fine.

Here is a my code:
```
library(RAdwords)
google_auth <- doAuth()
MyAdwordsData <- getData(
	clientCustomerId = 'XXX-XXX-XXXX',google_auth,statement(
            select = c('Url','AdGroupName','Impressions','Clicks'),
            report = 'URL_PERFORMANCE_REPORT',
            start = '2017-07-01',
            end = '2017-07-01'))
```
And here is the error message that I get:
```
Error in function (type, msg, asError = TRUE)  : 
  SSL certificate problem: unable to get local issuer certificate
```
Here is my session info:
```
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Portuguese_Portugal.1252  LC_CTYPE=Portuguese_Portugal.1252   
[3] LC_MONETARY=Portuguese_Portugal.1252 LC_NUMERIC=C                        
[5] LC_TIME=Portuguese_Portugal.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RAdwords_0.1.13

loaded via a namespace (and not attached):
[1] compiler_3.4.1 rjson_0.2.15   tools_3.4.1    RCurl_1.95-4.8 bitops_1.0-6
```

**Comment by jburkhardt** [comment]
@eviling  You closed the issue. Could you fix the issue?
@AlexandreCV  Thank you for the report.

I do not experience any issues running on Mac OS and Ubuntu. This seems to be an issue related to SSL and Windows. @AlexandreCV  Could you install this special build for curl as described here: https://github.com/jeroen/curl/issues/122

**Comment by jburkhardt** [comment]
@eviling  @AlexandreCV  Do you have the latest version of **RCurl** installed?
What does the R console respond to:
```
system.file("CurlSSL", "ca-bundle.crt", package = "RCurl")
```

Alternatively, you can try the following line in a fresh and clean R session (workspace) before your usual code:
```
curlGlobalInit(flags = c("ssl", "win32"))
```

**Comment by jburkhardt** [comment]
https://github.com/jburkhardt/RAdwords/issues/47

**Comment by olga-I-loveR** [comment]
I have the same issue starting Yesterday evening!

**Comment by djuery** [comment]
I also dare say I have the same issue starting today.

I could solve it modifying the getData function and especially this part:
```
data <- RCurl::getURL(paste("https://adwords.google.com/api/adwords/reportdownload/v", apiVersion, sep = ""), httpheader = c(Authorization = google.auth, developerToken = credlist$auth.developerToken, clientCustomerId = clientCustomerId, includeZeroImpressions = includeZeroImpressions), postfields = statement, verbose = verbose, cainfo = cert, ssl.verifypeer = TRUE)
```

If you remove `cainfo = cert` it just works...

**Comment by olga-I-loveR** [comment]
@jburkhardt the first one gets me this 
C:/Users/username/Documents/R/win-library/3.3/RCurl/CurlSSL/ca-bundle.crt"

**Comment by olga-I-loveR** [comment]
@djuery I use Radwords getdata function. How can I modify it?
Thanks!

**Comment by jburkhardt** [comment]
@djuery I comment/excluded ```cainfo = cert``` and pushed to the master branch.
@olga-I-loveR  @eviling  @AlexandreCV Please reinstall **RAdwords** from the github repository and test if the error still occurs:
```
require(devtools)
install_github('jburkhardt/RAdwords')
```
I am waiting on your feedback since I cannot test on windows. Mac and Ubuntu are fine.

**Comment by djuery** [comment]
@olga-I-loveR In order to fix the problem temporarily, you can try using:
```
getData <- function (clientCustomerId, google_auth, statement, apiVersion = "201708",
                     transformation = TRUE, changeNames = TRUE, includeZeroImpressions = FALSE,
                     verbose = FALSE)
{
  access <- google_auth$access
  credlist <- google_auth$credentials
  if (as.numeric(Sys.time()) - 3600 >= access$timeStamp) {
    access <- refreshToken(google_auth)
  }
  google.auth <- paste(access$token_type, access$access_token)
  cert <- system.file("CurlSSL", "ca-bundle.crt", package = "RCurl")
  data <- RCurl::getURL(paste("https://adwords.google.com/api/adwords/reportdownload/v",
                              apiVersion, sep = ""), httpheader = c(Authorization = google.auth,
                                                                    developerToken = credlist$auth.developerToken, clientCustomerId = clientCustomerId,
                                                                    includeZeroImpressions = includeZeroImpressions), postfields = statement,
                        verbose = verbose, ssl.verifypeer = TRUE)
  valid <- grepl(attr(statement, "reportType"), data)
  if (transformation & valid) {
    data <- transformData(data, report = attributes(statement)$reportType,
                          apiVersion = apiVersion)
    if (changeNames) {
      data <- changeNames(data)
    }
  }
  data
}
```

If you want to be 100% sure to map and warp to the correct function, you can call it `getDataFIX` so that you can call `getDataFIX` then to query your API data.

I'm quite busy with some project today so I can't figure out a better answer for now, maybe @jburkhardt will have one before me.
I think the problem is coming from the SSL certificates used within RCurl.

**Comment by djuery** [comment]
@jburkhardt What a fast reply :smile: 
I'll try your solution using devtools and will let you know.

**Comment by olga-I-loveR** [comment]
@jburkhardt Thanks a lot it works!

**Comment by AlexandreCV** [comment]
A colleague of mine experienced the same problem and found a solution to this issue.

Installing the special build of curl or running the `curlGlobalInit(flags = c("ssl", "win32"))` function didn't solve the issue for us.

We found that in our case the issue was related to the files "**ca-bundle.crt**" and "**cacert.pem**". For some reason, it seems that the original "ca-bundle.crt" file got corrupted.

We had to go to the directory with the RCurl installation files:
```
C:\Users\Alexandre\Documents\R\win-library\3.4\RCurl\CurlSSL
```
We modified the name of the original "ca-bundle.crt" to some random name so that it would no longer be used (we didn't delete it to keep it as a backup).

Finally, we copied the file "cacert.pem" and named the copy exactly "ca-bundle.crt". We also kept the original "cacert.pem" file intact.

After doing this the RAdwords queries worked back again correctly for us.

Thank you @jburkhardt for the recommendations! Best regards -

**Comment by jburkhardt** [comment]
@AlexandreCV Thank you! This is a very interesting finding!
However could you please test if my bug fix is working for you too by installing the package from the github repo? If this woks for you as well we could continue the package development without explicitly refering to the .crt file and leave this to the RCurl default settings.

**Comment by eviling** [comment]
Thanks @jburkhardt your bug works. Sorry for my delay, I use GA from work.

**Comment by AlexandreCV** [comment]
Sorry for the delay @jburkhardt . I've installed the development version and the RAdwords queries worked perfectly fine. Now I also updated to the latest CRAN version, working fine as well. Thanks again

**Comment by mhein19** [comment]
After pasting the developer token into the console I get the same error again:

> Error in function (type, msg, asError = TRUE)  : 
>   SSL certificate problem: unable to get local issuer certificate

![radwords_error](https://user-images.githubusercontent.com/39368327/40168765-996d13ba-59c4-11e8-806a-1dffc1f8a8fc.png)

Can anyone help me on this issue?
