### ISSUE TITLE
issue retrieving data

### ISSUE THREAD

**Issue by davidloris** [jburkhardt/RAdwords#72]
I get the following error when trying to query the API. It worked seamlessly until a few days ago:

Error in function (type, msg, asError = TRUE)  : 
  SSL: certificate verification failed (result: 5)

Any idea on how to solve this?

**Comment by jburkhardt** [comment]
See this issue here:
https://github.com/jburkhardt/RAdwords/issues/71
Should be fixed already on github master. Please reinstall package from github repo.
