### ISSUE TITLE
Click Performance Report

### ISSUE THREAD

**Issue by DrDiscoChimp** [jburkhardt/RAdwords#74]
I am having trouble getting the click performance report to work. Other reports work fine for me.

The code I am using to call the report is 
```

body <- statement(select = "CampaignId",
                  report="CLICK_PERFORMANCE_REPORT")



Adwords_data <- RAdwords::getData(clientCustomerId=customer_id,
                                  google_auth=google_auth,
                                  statement=body)
```
Do you have any advice for me?

I appreciate your time, and I appreciate the work you have put into this package. In general, it is awesome.

**Comment by jburkhardt** [comment]
@DrDiscoChimp 
There are two limitations with the ```CLICK_PERFORMANCE_REPORT```:
1. Data are only available for a single day and not a date range.
2. Click Performance Report cannot be retrieved for more than 90 days back.

If you adjust the ```statement``` as following it should work:
```R
body <- statement(select = "CampaignId",
                  report="CLICK_PERFORMANCE_REPORT",
                  start = "2017-11-01",
                  end = "2017-11-01")
```
For future debuging popuses: If you have any trouble with one of the reports you can display the API error log by setting ```transformation = F, changeNames = F``` inside ```getData()```.
```R
Adwords_data <- RAdwords::getData(clientCustomerId=customer_id,
                                                          google_auth=google_auth,
                                                          statement=body,
                                                          transformation = F,
                                                          changeNames = F)
```
