### ISSUE TITLE
SSL Certificate Problem on Ubuntu 14.04.5LTS

### ISSUE THREAD

**Issue by johnschoofs** [jburkhardt/RAdwords#75]
Hello @jburkhardt, 

I've been using your RAdwords package for a while and have seen a lot of benefit from it. Thank you for creating it! 

I'm running into the SSL certificate problem error on Ubuntu 14.04.5LTS within Rstudio server. The strange thing is I can run my code via ssh with no issues. I run via cd-ing to the directory and then Rscript filename.R. I'm running R version 3.3.3 RC with the newest version of your library (0.1.14).  

This issue came up after resuming work on Monday (12/4/2017).  Below is the code I've written: 

require(RAdwords)
require(googleAuthR)

account_number <- c("xxx-xxx-xxxx", "yyy-yyy-yyyy")

google_authorization <- doAuth()

start_date <- Sys.Date() - 30
end_date <- Sys.Date() - 1

get_impression_share_data <-
  function(customerId, s_date, e_date) {
    impression_share <- statement(
      select = c(
        'CampaignName',
        'Impressions',
        'Clicks',
        'Cost',
        'AverageCpc',
        'Ctr',
        'SearchBudgetLostImpressionShare',
        'SearchRankLostImpressionShare',
        'SearchImpressionShare'
      ),
      report = "CAMPAIGN_PERFORMANCE_REPORT",
      start = s_date,
      end = e_date
    )
    
    impression_share_data <- RAdwords::getData(
      clientCustomerId = customerId,
      google_auth = google_authorization,
      statement = impression_share,
      transformation = T,
      changeNames = T
    )
    return(impression_share_data)
  }

for (i in 1:length(account_number)){
  impression_share <- get_impression_share_data(account_number[i], start_date, end_date)
}

Thank you in advance for your help!

**Comment by jburkhardt** [comment]
Hi @johnschoofs

could you please provide the error message? After which line of code execution do you get the error? What RAdwords version do you use?

I am wondering why you are using ```require(googleAuthR)```? If you only connect to the Adwords API you do not need the package **googleAuthR**, since **RAdwords** has its own authentication process.

We do not have any SSL issues neither with RStudio Server nor with Ubuntu Server nor Mac OS.
