### ISSUE TITLE
Error: object 'google_auth' not found

### ISSUE THREAD

**Issue by sayac007** [jburkhardt/RAdwords#76]
Dear Mr. Burkhardt, I am currently trying to load reporting data from Google Adwords using Your library RAdwords. Everything works fine (reports and metrics commands work well) but for some reason after "google_auth <- doAuth(save=TRUE)" the "google_auth" object is cannot be accessed from the getData command: "Error: object 'google_auth' not found". Can you please help?

During the authentification, this error message is received: "Error in rjson::fromJSON(RCurl::postForm("https://accounts.google.com/o/oauth2/token",  : 
  STRING_ELT() can only be applied to a 'character vector', not a 'raw'"

I use the latest CRAN version of RAdwords, RStudio 1.0.153 and MRO 3.4.0. The SSL connection goes via proxy server (saved in the ".Renviron" file) but as I said I get the list of reports and metrics without any problems so I don't think that it is a proxy issue.

**Comment by jburkhardt** [comment]
@sayac007 Please provide your code. Otherwise, it is difficult to help you. The list of ```reports()``` and ```metrics()``` is loaded locally from the package installation and has nothing to do with the SSL connection.

**Comment by sayac007** [comment]
This was a firewall issue, everything works fine if the computer is not under firewall. Thanks for support!
