### ISSUE TITLE
error message: "!!!1|||-1|||ReportInfoError.REPORT_INFO_ERROR @ selector; errorDetails:Xml converter missing for WebApiVersion V201609???"

### ISSUE THREAD

**Issue by Mmadmar** [jburkhardt/RAdwords#77]
Hi all,

I am trying to use RAdwords in an RStudio Server environment. Below is the code

```
library(RAdwords)
google_auth <- doAuth()

data_1 <- data.frame()

body_1 <- statement(select=c('Date','Cost', 'CampaignName'),
                    report="CAMPAIGN_PERFORMANCE_REPORT",
                    start="2017-01-01",
                    end="2017-01-31")

clientId_arg = "XXX-XXX-XXXX" # I am using a real client_id here

data_1 <- getData(clientCustomerId=clientId_arg,
                  google_auth=google_auth,
                  statement=body_1) 
print(data_1)
```

On RStudio desktop, the code is running fine. But on the server I get the following output:

`"!!!1|||-1|||ReportInfoError.REPORT_INFO_ERROR @ selector; errorDetails:Xml converter missing for WebApiVersion V201609???"`

I was not able to find any help using google.

Does anyone have an idea?
Many Thanks!

**Comment by jburkhardt** [comment]
Hi,
which **RAdwords** version do you use?
It looks like you are using an old version of **RAdwords** that tries to connect with the Adwords API version v201609. This API version is deprecated. Please reinstall the package. The latest RAdwords version is 0.1.14 which connects with the Google Adwords API v201708.
Hope that helps!

**Comment by Mmadmar** [comment]
Hi,

thanks for your quick answer.
We have been able to solve this by upgrading to R Version 3.4.3.

Many Thanks!
