### ISSUE TITLE
retrieve final form of curl request

### ISSUE THREAD

**Issue by sgoley** [jburkhardt/RAdwords#79]
Just wanted to say that I love the project and it has been very useful. Hoping to find the time to contribute in the near future.  
Out of curiosity, I have this question. 

When I look at the verbose output for the curl request - I can see everything except the final form for the actual reportDefinition / AWQL request. 
![2018-02-28 17_22_53-rstudio](https://user-images.githubusercontent.com/10283176/36816586-3510a558-1cac-11e8-8773-275e300995cf.png)

I was wondering if there was a way to see that as in this kind of output from another rest client "Insomnia".

![2018-02-28 17_26_58-adwords generate report](https://user-images.githubusercontent.com/10283176/36816778-ddc33fee-1cac-11e8-99ed-570f41bbed4b.png)

**Comment by jburkhardt** [comment]
The ```statement``` function creates the awql query. 
Example:
```R
statement(select = c('Date',
+                      'CampaignName',
+                      'Impressions',
+                      'Clicks',
+                      'AveragePosition',
+                      'Cost',
+                      'Ctr',
+                      'Conversions'),
+           report = "CAMPAIGN_PERFORMANCE_REPORT",
+           start = "2017-01-01",
+           end = "2017-01-01")
[1] "__rdquery=SELECT+Date,CampaignName,Impressions,Clicks,AveragePosition,Cost,Ctr,Conversions+FROM+CAMPAIGN_PERFORMANCE_REPORT+DURING+20170101,20170101&__fmt=CSV"
```
Find out more about awql here: https://developers.google.com/adwords/api/docs/guides/awql
