### ISSUE TITLE
Fatal error: Session aborted

### ISSUE THREAD

**Issue by eatom** [jburkhardt/RAdwords#80]
Hi,

I get a critical R studio fatal error - session aborted as soon as I use the getData() function. 

Can you look into this? If yes what sort of information do you need? 

Kind regards
E

**Comment by mbannert** [comment]
How about what's the fatal error (screen shot) or error message :) ?
 Also,
- can you try to run it outside R studio? 
- can you re-run /w debug(getData) before and tell us where it breaks? 
- R version, R studio version, R Adwords, your OS etc would be nice.

**Comment by eatom** [comment]
WoW that was a quick reply 👍 

Here are the info: 
R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
R studio Version 1.1.383 
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Rdwords version: 0.1.15

here is what I get when running in R (not R studio), 

`*   Trying 172.217.16.45...
* TCP_NODELAY set

 *** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: .Call("fromJSON", json_str, unexpected.escape, PACKAGE = "rjson")
 2: rjson::fromJSON(RCurl::postForm("https://accounts.google.com/o/oauth2/token",     .opts = opts, code = credlist$c.token, client_id = credlist$c.id,     client_secret = credlist$c.secret, redirect_uri = "urn:ietf:wg:oauth:2.0:oob",     grant_type = "authorization_code", style = "POST"))
 3: loadToken(credentials)
 4: doAuth()
 5: eval(ei, envir)
 6: eval(ei, envir)
 7: withVisible(eval(ei, envir))
 8: source("/Users/EmiL/some_FOLDER/r-adwords.R")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
* Connected to accounts.google.com (172.217.16.45) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google Inc; CN=accounts.google.com
*  start date: Feb 13 10:58:12 2018 GMT
*  expire date: May  8 10:40:00 2018 GMT
*  subjectAltName: host "accounts.google.com" matched cert's "accounts.google.com"
*  issuer: C=US; O=Google Inc; CN=Google Internet Authority G2
*  SSL certificate verify ok.
> POST /o/oauth2/token HTTP/1.1Selection: 
Host: accounts.google.com
Accept: */*
Content-Length: 266
Content-Type: application/x-www-form-urlencoded
* upload completely sent off: 266 out of 266 bytes
< HTTP/1.1 200 OK
< X-Content-Type-Options: nosniff charset=utf-8
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: Mon, 01 Jan 1990 00:00:00 GMT
< Date: Mon, 05 Mar 2018 17:23:17 GMT
< Content-Disposition: attachment; filename="json.txt"; filename*=UTF-8''json.txt
< Server: ESF
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< Alt-Svc: hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"
< Accept-Ranges: none
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< 
* Connection #0 to host accounts.google.com left intact
`

And included the screen shot from R :-) 
<img width="539" alt="screen shot 2018-03-05 at 18 27 15" src="https://user-images.githubusercontent.com/33755019/36989839-3470fe2c-20a3-11e8-9f75-97a56adcc1a0.png">

**Comment by eatom** [comment]
I re-installed all the packages that I had and it fixed the issue.
