### ISSUE TITLE
error message when trying to connect to new mcc

### ISSUE THREAD

**Issue by davidloris** [jburkhardt/RAdwords#81]
I set up the credentials in console.developers.google.com. I have basic access dev token and have standard access to the mcc.

I then run:
google_auth <- doAuth()

when prompted I include the client id, client secret and developer token. After this I get the following error message:

Error in function (type, msg, asError = TRUE)  : 
  SSL: certificate verification failed (result: 5)

Do you have any advice on trouble shooting?

**Comment by jburkhardt** [comment]
Hi @davidloris 

could you please provide more information about your:

- OS
- R version
- RAdwords version
- RStudio
- Do you connect to a the new MCC in a R project that has been connected to another MCC before?

**Comment by davidloris** [comment]
thank @jburkhardt

**Comment by jburkhardt** [comment]
Did you set up a new RStudio project for the new MCC?
If not, there might be an existing authentication file ```.google.auth.RData``` in your working directory, that handles the auth process for the already existing MCC connection. This might lead to a conflict between the two MCCs. Please check if this is the case and make a new RStudio project if necessary.

**Comment by davidloris** [comment]
thanks! that was the problem. its working now
