### ISSUE TITLE
How to add segment in the getData function

### ISSUE THREAD

**Issue by simran-k** [jburkhardt/RAdwords#86]
`  campaignDetails<- RAdwords::getData(clientCustomerId=id, google_auth=google_auth ,statement=body8) `

Where would I add HourOfDay segment here?

body8 looks like this
`body8 <- statement(select=c('CampaignId', 'CampaignName', 'Cost', 'CostPerConversion','Date', 'AllConversionRate', 'AllConversions', 'AllConversionValue', 'AverageCost', 'AverageCpc', 'AverageCpc', 'AverageCpe','AverageCpm',  'Amount', 'BaseCampaignId', 'Ctr', 'Clicks'),report="CAMPAIGN_PERFORMANCE_REPORT",start=maxDate, end=yesterdayDate)
`

**Comment by jburkhardt** [comment]
The Adwords API does not allow to query the metric ```ÀllConversions``` and  ```HourOfDay``` at once. The API response is: ```Cannot select a combination of AllConversionValue and HourOfDay```.

Instead, you should use ```Conversions```as a metric. The following query should work for you:

```R
body <- statement(select=c('CampaignId',
                           'CampaignName',
                           'Cost',
                           'CostPerConversion',
                           'Date',
                           #'AllConversionRate',
                           #'AllConversions',
                           #'AllConversionValue',
                           'Conversions',
                           'AverageCost',
                           'AverageCpc',
                           'AverageCpc',
                           'AverageCpe',
                           'AverageCpm',
                           'Amount',
                           'BaseCampaignId',
                           'Ctr',
                           'Clicks',
                           'HourOfDay'),
                  report="CAMPAIGN_PERFORMANCE_REPORT",
                  start="2018-01-01",
                  end="2018-01-01")
```
