### ISSUE TITLE
doAuth() Authentication Issue

### ISSUE THREAD

**Issue by anthonypiccolo** [jburkhardt/RAdwords#87]
Hi,

I was wondering if someone could help - I run `google_auth <- doAuth()` insert the client ID, secret key and then the developer token but it doesn't load the webpage with the string. Instead all I get is;

`Error in function (type, msg, asError = TRUE)  : 
  Failed to connect to accounts.google.com port 443: Connection refused`

Can someone please assist with this? I created the OAuth 2.0 client ID and secret in a Google API project. I've tried regenerating the developer token and client secret but that doesn't seem to work.

Thanks!

**Comment by jburkhardt** [comment]
Hi @anthonypiccolo 

Thank you for using **RAdwords**!

Did you follow these steps during authentication: http://jburkhardt.github.io/RAdwords/auth/

Could you provide the following information please:

- Operating System
- R Version
 - RAdwords version
 - the R code which leads to the error
 - the error message, prompt output
 - code as text rather than screenshots

**Comment by anthonypiccolo** [comment]
Hey @jburkhardt 

Thanks for helping out!

Yep, followed the official documentation.

Operating System: Windows 7
R Version: 3.4.4
RAdwords: 0.1.16
R code which leads to error: This is when I run `google_auth <- doAuth()` and it happens after I get asked to provide the developer token (after I have already given the client id/secret)
Error Message: `Error in function (type, msg, asError = TRUE) : Failed to connect to accounts.google.com port 443: Connection refused`
Code: `google_auth <- doAuth()`  then prompted for client id, then client secret and then developer token. Once I hit enter on the developer token part is when I get the error message.

Hope this gives you enough information to help me solve the issue.

Thanks,
Anthony

**Comment by gmlgml1230** [comment]
Hi @jburkhardt  
  
I get the error below as the existing issue #71, but It's not the same error above issue #87.  
  
```
Error in function (type, msg, asError = TRUE)  :   
  SSL certificate problem: unable to get local issuer certificate  
```  
  
Previously, I noticed this error in getData, but now this error happens in getAuth.  
  
```  
RCurl::getURL(url, cainfo=cert, ssl.verifypeer = TRUE)  
```  
  
I do not understand why I put this the above part.  
  
If you remove 'cainfo = cert' it just works.

**Comment by jburkhardt** [comment]
@gmlgml1230  @anthonypiccolo 
I made some changes to the code and pushed it to a new branch: https://github.com/jburkhardt/RAdwords/commit/297aba9ff571cd23a3e6371e219a9e406e6a5db3

Could you please reinstall the package from this branch with the code below and test again:

```R
require(devtools)
install_github('jburkhardt/RAdwords', ref = "do_auth_curl_ssl")
```

**Comment by gmlgml1230** [comment]
I tested it on linux and window10, and the previous error no longer occurs.  
  
Thanks!

**Comment by jburkhardt** [comment]
@gmlgml1230  Thank you for testing. I merged the code into the master branch. You can now go with the package installation from there:
```
require(devtools)
install_github('jburkhardt/RAdwords')
```
