### ISSUE TITLE
Problem with GEO_PERFORMANCE_REPORT

### ISSUE THREAD

**Issue by chipoglesby** [jburkhardt/RAdwords#9]
When I create my query to pull info from the geo performance report, it doesn't return any data.

Here's the query (minus the client ID):
body <- statement(select=c('Date', 'Impressions', 'Clicks', 'RegionCriteriaId'), 
                  report="GEO_PERFORMANCE_REPORT",
                  where="Impressions >0",
                  start="20130101", 
                  end="20141229")
data <- getData(clientCustomerId='xxx-xxx-xxxx',statement=body,transformation=TRUE, google_auth=google_auth)

Here's the result:

str(data)
'data.frame':	0 obs. of  29 variables:
 $ NA: Factor w/ 1 level "<?xml version=1.0 encoding=UTF-8 standalone=yes?><reportDownloadError><ApiError><type>SelectorError.MISSING_FIELDS</type><trigg"| __truncated__: 
 $ NA: Factor w/ 1 level " CustomFeatureCriteriaId": 
 $ NA: Factor w/ 1 level " CustomOtherCriteriaId": 
 $ NA: Factor w/ 1 level " CustomCountryCriteriaId": ......

**Comment by jburkhardt** [comment]
Hi Chip,
did you try ```transformation=FALSE``` to see if the API delivers the raw data?
I don´t know if location based data are available on account level. Maybe you have to add ```CampaignName``` as an additional selector.
If there should be anything wrong with the package I will look into it next week.
Regards,
Johannes

**Comment by jburkhardt** [comment]
Hi Chip,
I found the solution to your problem. If you want to pull data with the ```GEO_PERFORMANCE_REPORT``` you have to use one of the following variables as additional selector:
```
CountryCriteriaId, CustomFeatureCriteriaId, CustomOtherCriteriaId, CustomCountryCriteriaId, CustomRegionCriteriaId, CustomTerritoryCriteriaId, CustomProvinceCriteriaId, CustomStateCriteriaId, CustomPrefectureCriteriaId, CustomGovernorateCriteriaId, CustomCantonCriteriaId, CustomUnionTerritoryCriteriaId, CustomAutonomousCommunityCriteriaId, CustomDMARegionCriteriaId, CustomMetroCriteriaId, CustomCongressionalDistrictCriteriaId, CustomCountyCriteriaId, CustomMunicipalityCriteriaId, CustomCityCriteriaId, CustomPostalCodeCriteriaId, CustomDepartmentCriteriaId, CustomAirportCriteriaId, CustomTVRegionCriteriaId, CustomOkrugCriteriaId, CustomBoroughCriteriaId, CustomCityRegionCriteriaId, CustomArrondissementCriteriaId, CustomNeighborhoodCriteriaId, CustomUniversityCriteriaId
```

For instance following example works for me:
```
bodyGeo <- statement(select=c('CountryCriteriaId','Clicks','CampaignName ','Date'),
                  report="GEO_PERFORMANCE_REPORT",
                  start="20140320",
                  end="20140321")

data <- getData(clientCustomerId='***-***-****',
                google_auth = google_auth,
                statement=bodyGeo,
                transformation = T)
```

**Comment by chipoglesby** [comment]
That works! Thank you!

**Comment by prasoonsrivas** [comment]
Hi
while using 'CountryCriteriaId' or RegionCriteriaId or CityCriteriaId  in fetching data , it comes with Number like 2356 ,  why is not showing name of the country region ,city etc plz help

**Comment by jburkhardt** [comment]
RAdwords extracts data from the ```Google Adwords API Reporting Service```. Data are retrieved as stored by Google. In case of geo/location attributes Google only provides IDs instead of names within the ```Reporting Service```. Further reading here: https://developers.google.com/adwords/api/docs/appendix/reports/geo-performance-report  
In order to get the names corresponding with the IDs you have to query the [Location Criterion Service](https://developers.google.com/adwords/api/docs/reference/v201607/LocationCriterionService). RAdwords is not capable to query the ```Criterion Service```.

**Comment by ArbenKqiku** [comment]
> Hi Chip,
> I found the solution to your problem. If you want to pull data with the `GEO_PERFORMANCE_REPORT` you have to use one of the following variables as additional selector:
> 
> ```
> CountryCriteriaId, CustomFeatureCriteriaId, CustomOtherCriteriaId, CustomCountryCriteriaId, CustomRegionCriteriaId, CustomTerritoryCriteriaId, CustomProvinceCriteriaId, CustomStateCriteriaId, CustomPrefectureCriteriaId, CustomGovernorateCriteriaId, CustomCantonCriteriaId, CustomUnionTerritoryCriteriaId, CustomAutonomousCommunityCriteriaId, CustomDMARegionCriteriaId, CustomMetroCriteriaId, CustomCongressionalDistrictCriteriaId, CustomCountyCriteriaId, CustomMunicipalityCriteriaId, CustomCityCriteriaId, CustomPostalCodeCriteriaId, CustomDepartmentCriteriaId, CustomAirportCriteriaId, CustomTVRegionCriteriaId, CustomOkrugCriteriaId, CustomBoroughCriteriaId, CustomCityRegionCriteriaId, CustomArrondissementCriteriaId, CustomNeighborhoodCriteriaId, CustomUniversityCriteriaId
> ```
> 
> For instance following example works for me:
> 
> ```
> bodyGeo <- statement(select=c('CountryCriteriaId','Clicks','CampaignName ','Date'),
>                   report="GEO_PERFORMANCE_REPORT",
>                   start="20140320",
>                   end="20140321")
> 
> data <- getData(clientCustomerId='***-***-****',
>                 google_auth = google_auth,
>                 statement=bodyGeo,
>                 transformation = T)
> ```

Hi,

When trying to run your code above, I get an empty table. Do you know why that is? Thank you!
