### ISSUE TITLE
getData() returns strange string

### ISSUE THREAD

**Issue by thomiko** [jburkhardt/RAdwords#93]
We have created an authentication RData file with the API token of our company. Using this token the R script works flawlessly on the computers of two people when we retrieve a CAMPAIGN_PERFORMANCE_REPORT via RAdwords. On the computer of a third person we always get a strange string return value (after less than a second) when running exactly the same script (no matter if it's being run inside RStudio or called from a batch file):

![radwords 1](https://user-images.githubusercontent.com/16490122/44142948-2d2715f2-a082-11e8-849b-1f77339fd29b.png)

This is the code being used to retrieve the CAMPAIGN_PERFORMANCE_REPORT:

![radwords 2](https://user-images.githubusercontent.com/16490122/44143210-151ee1a0-a083-11e8-97c4-94299627e0b8.png)

Here's the result on the computers of the first two people:

![radwords 3](https://user-images.githubusercontent.com/16490122/44143146-d8fe3c3e-a082-11e8-9db5-4bed79a605e7.png)

Anyone any ideas what it means and why it happens? Thanks! 

We are all using Windows 7.

**Comment by jburkhardt** [comment]
Hi @thomiko 
Thank you for the input!
Could you please print the faulty variable Output in the R Console prompt and paste it here? Maybe it contains an error message from the Adwords API. Furthermore, what OS, R Version, R Studio Version and RAdwords Version do you use on the faulty computer? Maybe something is outdated.

**Comment by jburkhardt** [comment]
Fine that you are set up now on all three machines!
The auth file is still the same, however RAdwords 0.1.14 communicates with a deprecated Adwords API version. The Adwords API updates several times a year. To ensure that your code is running in future just make sure that you update to the latest RAdwords version regularly.
